### ISSUE TITLE
Fonctionalité barres de départ, pas de taille standard

### ISSUE THREAD

**Issue by rcharb1** [pierre-H/optimiseur-coupe#10]
Bonjour,
Je suis en train de réfléchir sur l'ajout de la possibilité pour l'utilisateur d'avoir des barres de départ de différentes tailles.
Cet ajout donne un niveau supplémentaire de combinaison. En effet, l'algorithme pour le moment est le de mettre le premier tronçon dans une barre, n'importe laquelle puisqu'elles ont toutes la même taille, et de combiner toutes le possibilités une par une en ne retenant que les meilleures. Puis on met une autre barre au départ et on recommence. Au final, on garde la solution qui a le meilleur rendement, on supprime les tronçons utilisés par cette combinaison dans la liste des tronçons demandés, puis on refait la même opération jusqu'à ce qu'il n'y ait plus de tronçons dans la liste des tronçons.
Maintenant qu'on veut rajouter la possibilité d'avoir différentes longueurs au début, ça rajoute un niveau de combinaison, ce qui n'est pas négligeable tant du point de vue de la charge de calcul, que de la remanipulation des structures de données.
D'un autre côté, ça semble presque indispensable pour le réalisme du programme, non ?

PS : Quand j'utilise le programme, j'obtiens maintenant une erreur de segmentation à l'exécution alors qu'avant, ça marchait bien. Je ne me suis pas encore plongée dans le code, qui sait, peut-être quelqu'un a-t-il une idée de ce qui a pu être modifié depuis qui a pu causer ce bug ?

**Comment by ninja427** [comment]
Le 2015-04-27 12:04, rcharb1 a écrit :

> Bonjour,
>  Je suis en train de réfléchir sur l'ajout de la possibilité pour
> l'utilisateur d'avoir des barres de départ de différentes tailles.
>  Cet ajout donne un niveau supplémentaire de combinaison. En effet,
> l'algorithme pour le moment est le de mettre le premier tronçon dans
> une barre, n'importe laquelle puisqu'elles ont toutes la même taille,
> et de combiner toutes le possibilités une par une en ne retenant que
> les meilleures. Puis on met une autre barre au départ et on
> recommence. Au final, on garde la solution qui a le meilleur
> rendement, on supprime les tronçons utilisés par cette combinaison
> dans la liste des tronçons demandés, puis on refait la même opération
> jusqu'à ce qu'il n'y ait plus de tronçons dans la liste des tronçons.
>  Maintenant qu'on veut rajouter la possibilité d'avoir différentes
> longueurs au début, ça rajoute un niveau de combinaison, ce qui n'est
> pas négligeable tant du point de vue de la charge de calcul, que de 
> la
> remanipulation des structures de données.
>  D'un autre côté, ça semble presque indispensable pour le réalisme du
> programme, non ?
> 
> PS : Quand j'utilise le programme, j'obtiens maintenant une erreur de
> segmentation à l'exécution alors qu'avant, ça marchait bien. Je ne me
> suis pas encore plongée dans le code, qui sait, peut-être quelqu'un
> a-t-il une idée de ce qui a pu être modifié depuis qui a pu causer ce
> bug ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] https://github.com/pierre-H/optimiseur-coupe/issues/10

Je suis parvenu strictement aux mêmes conclusions que toi...
Maintenant on peut aussi partir du principe que les barres de départ 
font toutes la même taille (cas général : un stock de barres + 1 grande 
chute d'une série précédente), du coup ça impose à l'utilisateur de 
faire deux saisies différentes (une spécifique pour la chute).
On peut aussi transformer l'algorithme en lui disant de taper dans 
toutes les barres en commençant par les plus petites (car l'intérêt au 
final est d'avoir les plus grandes chutes possibles, et donc de se 
débarasser des petites barres dès que possible). Ce qui revient à dire 
que pour chaque nouvelles barre l'algorithme vient se servir dans une 
liste triée par ordre de taille croissante. Du coup ça ne devrait guère 
surcharger le programme.

Qu'en pensez-vous ?

P. S. : J'ai bien exploré ton code Rebecca et je me répète : j'aime 
beaucoup ta façon de coder, c'est vraiment très très propre ! (Quand je 
serai grand, je veux coder comme toi). Tu as appris le c++ avant la 

## formation ?

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by ninja427** [comment]
Le 2015-04-27 12:17, Xavier JANIN a écrit :

> Le 2015-04-27 12:04, rcharb1 a écrit :
> 
> > Bonjour,
> >  Je suis en train de réfléchir sur l'ajout de la possibilité pour
> > l'utilisateur d'avoir des barres de départ de différentes tailles.
> >  Cet ajout donne un niveau supplémentaire de combinaison. En effet,
> > l'algorithme pour le moment est le de mettre le premier tronçon dans
> > une barre, n'importe laquelle puisqu'elles ont toutes la même 
> > taille,
> > et de combiner toutes le possibilités une par une en ne retenant que
> > les meilleures. Puis on met une autre barre au départ et on
> > recommence. Au final, on garde la solution qui a le meilleur
> > rendement, on supprime les tronçons utilisés par cette combinaison
> > dans la liste des tronçons demandés, puis on refait la même 
> > opération
> > jusqu'à ce qu'il n'y ait plus de tronçons dans la liste des 
> > tronçons.
> >  Maintenant qu'on veut rajouter la possibilité d'avoir différentes
> > longueurs au début, ça rajoute un niveau de combinaison, ce qui 
> > n'est
> > pas négligeable tant du point de vue de la charge de calcul, que de 
> > la
> > remanipulation des structures de données.
> >  D'un autre côté, ça semble presque indispensable pour le réalisme 
> > du
> > programme, non ?
> > 
> > PS : Quand j'utilise le programme, j'obtiens maintenant une erreur 
> > de
> > segmentation à l'exécution alors qu'avant, ça marchait bien. Je ne 
> > me
> > suis pas encore plongée dans le code, qui sait, peut-être quelqu'un
> > a-t-il une idée de ce qui a pu être modifié depuis qui a pu causer 
> > ce
> > bug ?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub [1].
> > 
> >  *
> > 
> > ## Links:
> > 
> > [1] https://github.com/pierre-H/optimiseur-coupe/issues/10
> 
> Je suis parvenu strictement aux mêmes conclusions que toi...
> Maintenant on peut aussi partir du principe que les barres de départ
> font toutes la même taille (cas général : un stock de barres + 1
> grande chute d'une série précédente), du coup ça impose à
> l'utilisateur de faire deux saisies différentes (une spécifique pour
> la chute).
> On peut aussi transformer l'algorithme en lui disant de taper dans
> toutes les barres en commençant par les plus petites (car l'intérêt 
> au
> final est d'avoir les plus grandes chutes possibles, et donc de se
> débarasser des petites barres dès que possible). Ce qui revient à 
> dire
> que pour chaque nouvelles barre l'algorithme vient se servir dans une
> liste triée par ordre de taille croissante. Du coup ça ne devrait
> guère surcharger le programme.
> 
> Qu'en pensez-vous ?
> 
> P. S. : J'ai bien exploré ton code Rebecca et je me répète : j'aime
> beaucoup ta façon de coder, c'est vraiment très très propre ! (Quand
> je serai grand, je veux coder comme toi). Tu as appris le c++ avant 
> la
> formation ?

## P.P.S. : Personnellement je n'ai rien modifié dans le repo

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
Je ne suis pas certaine d'avoir complètement compris ton raisonnement concernant l'algorithme alors je vais essayer de le reformuler et dis-moi si je suis dans le faux : Est-ce que tu veux dire que l'algorithme serait de commencer à "remplir" les petites barres ? Avant d'y aller avec la combinatoire brute, qu'on fasse des petits tatonnements du style "est-ce qu'il y a un segment demandé qui a exactement la taille d'une barre ?". Qu'est-ce qui doit être trié par ordre croissant ? La liste des barres de départ ou la liste des tronçons ?
Pour ce qui est de la solution hybride de proposer de réutiliser une chute et une seule, c'est vrai que ça simplifie la combinatoire, mais je crois que ça risque de faire un peu bizarre "s'il vous reste une chute de la dernière fois, entrez-là" ! Je penche plutôt sur le "tout ou rien" : ou proposer un algorithme qui accepte des barres de taille différente, ou non. Qu'en pense-tu ?

Merci encore pour tes encouragements concernant mon code. J'ai en fait appris le C++ sur le tas parce que je voulais faire ce projet en C++. Ce n'est après tout pas si différent du C et j'ai suivi un très bon cours sur le site du zéro...

**Comment by rcharb1** [comment]
Si on proposait effectivement cette fonctionnalité, j'ai encore du mal à déterminer le meilleur algorithme qui épargnerait la mémoire **et** les calculs. Pour info, voici l'algorithme actuel :
- Les tronçons sont triés par ordre croissant et indexés selon leur place dans la liste.
- Notons une ListPaires composée des tronçons 1, 5 et 6 (1, 5, 6) (autre notation dans le programme, mais bon...)
- On crée la ListPaires (1) et on mouline en créant la (1, 2), (1, 3), (1, 4) etc
- Pour chacune des ListPaires ainsi crées, on mouline de même, càd que la ListPaires (1, 3) donne naissance aux ListPaires (1, 3, 4), (1, 3, 5) (1, 3, 6) etc..
- Tout ça, c'est en commançant par le tronçon 1, mais on fait ce même raisonnement en commençant par le tronçon 2 ( (2), (2, 3), (2, 4) etc puis (2, 3, 4), (2,3,5) etc)
- Toute cette étape sert à déterminer quelle est la meilleure première combinaison à choisir. Pour économiser la mémoire et les calculs, on met en place deux facteurs contrôlant : 
  1. Pour ne pas encombrer la mémoire de millions de possibilités bidons, on met une barre d'exigence en dessous de laquelle on ne mémorise pas la combinaison.
  2. Pour économiser les calculs, les tronçons sont triés par ordre croissant. Ainsi, si la combinaison (1,  2, 4) a été refusée car elle est plus grande que la longueur de la barre, il n'est pas la peine d'essayer (1, 2, 5) car ce sera forcément plus grand. On abandonne donc en cours de route la branche (1, 2) pour passer à la branche (1, 3). Ainsi, au fur et à mesure, les feuilles de l'arbre se font plus pauvres et le calcul est réduit de moitié au moins (voir beaucoup plus, ça dépend des cas)

Si on adoptait la possibilité de différentes tailles de barres, je n'arrive pas à m'imaginer un algorithme qui nous assurerait le meilleur rendement, sans rentrer dans la folie... Peut-être aurais-tu une idée ? (si oui, tu peux me l'expliquer comme je viens de te le faire, en langage naturel...
Bonne journée !

**Comment by rcharb1** [comment]
Petite piste : peut-être associer la combinatoire brute avec des petits tâtonnements artisanaux qui peuvent nous mettre sur la piste : par exemple, "y a-t-il des combinaisons de 2 tronçons qui sont dans l'ordre de grandeur d'une de nos barres ?" On peut même utiliser ce truc avec des combinaisons de 3... Plus, à voir... Du coup, il faudra jongler entre cet aspect, et la combinatoire pure... Ce qui peut donner lieu à des algorithmes très compliqués...

PS :  on est dans un domaine que je trouve très compliqué, et j'ai toujours l'impression quand j'écris ce genre de message que je suis tellement "dans ma propre tête" que c'est peut-être dur pour quelqu'un d'autre de comprendre ce que je veux dire... Si c'est le cas, n'hésite pas à me faire répéter dans d'autres termes !

**Comment by rcharb1** [comment]
Note sur le bug : il s'agit du fait de supprimer le dernier élément d'une liste de tronçons qui cause l'erreur. Je n'ai pas encore réussi à trouver pourquoi, ni qu'est-ce que j'ai bien pu changer les derniers jours pour que ça se passe comme ça. Je vais jeter un coup d'oeil sur l'état des fichiers il y a quelques jours...

**Comment by ninja427** [comment]
En fait cela peut se résoudre très simplement, tu as déjà fait la majeure partie du boulot.
En fait actuellement, tu prends une barre (toujours la même), tu la passes à la moulinette, et là tu choisis quelle est la combinaison de coupes la plus rentable. Tu supprimes les tronçons consommés de la liste initiale afin de plus les réutiliser. Et tu passes une autre barre à la moulinette...
Le plus simple selon moi est de faire strictement la même chose mais au lieu d'utiliser toujours la même barre (qu'on aurait en x exemplaires), on utilise une barre provenant d'une liste de barres triées par ordre croissant. 
En gros ton main pourrait s'écrire:
int main()
{
    List \* l_tronçons = new List();
    List \* l_barres = new List();
    createSortedListUpToDown(l_tronçons,45.,23.,12.,54.,97.,45.6,87.,52.,41., 78.,1., 6., 7., 87., 25.,0.);
    createSortedListDownToUp(l_barres, 100., 100., 100., 100., 100., 60., 50., 0.);
    DoubleListPaires \* d = new DoubleListPaires(l_tronçons, l_barres);
    d->pilote ();
    return 0;
}

Les createSortedList modifiées ne sont même pas obligatoires, on pourrait utiliser la même fonction sous certaines conditions (parser la liste des barres depuis la fin pour commencer par la plus petite par exemple).

Comment justifier fonctionellement ceci ?
En fait c'est le point de vue de l'utilisateur qui nous sauvera. En effet, son intérêt est d'avoir la chute finale la plus longue possible (pour réutilisation).

Exemple concret:
J'ai une barre de 50 cm et 2 barres de 1 m, et je veux 5 tronçons de 25 cm. Peut-être que demain j'aurai besoin d'une barre de 80 cm, mais ce n'est pas sûr.
Je commence par la barre de 50 cm, je la consomme : il me reste 1 barre de 1 m et 1 de 25 cm
Je commence par les barres de 1 m, je consomme une barre de 1 m et il me reste une barre de 75 cm et une autre de 50 cm.

C'est une solution simple qui ne garantit peut-être pas directement le rendement maximal mais qui a le mérite de garantir les chutes les plus utiles à l'utilisateur. 

Un autre exemple qui amène à réfléchir:
Chute de 10 cm sur une barre de 50 cm -> rendement 80 %
Chute de 10 cm sur une barre de 100 cm -> rendement 90 %
Comment du coup pourrait-on se baser sur le rendement global pour choisir la solution occasionnant le moins de chutes entre plusieurs "organisations de barres" ?

Si on veut faire une solution parfaite, il faudrait faire la même chose que ce qui a été fait pour les tronçons, mais à une échelle supérieure, à savoir tester toutes les combinaisons de barres en entrée (et trouver la meilleure combinaison de découpes pour chacune d'entre elles) et choisir celle ayant le meilleur rendement global - pardon - la longueur cumulée de chutes (hors dernière barre) la plus courte possible. Je n'ose même pas imaginer les ressources nécessaires...

Tout ceci pour dire qu'on peut facilement justifier du point de vue de l'utilisateur de découper les barres en commençant par les plus petites et que le rendement redevient unitairement valable.

Qu'en pensez-vous ?

J'espère que mes explications sont claires, sinon je me tiens bien évidemment à votre disposition !

Bonne journée !

**Comment by rcharb1** [comment]
Oui, ça me paraît plausible comme algorithme... ça ne garantit pas **le** résultat parfait, mais ça optimise quand même, et comme tu le dis, ça permet d'avoir des chutes réutilisables...
De mon côté, je pensais plutôt à un algorithme de ce type :
- On effectue toutes les combinaisons possibles, sans encore savoir à quelle barre chacune des combinaisons peut s'appliquer.
- On "attache" ensuite à chaque combinaison la barre qui lui convient le mieux et on calcule le rendement correspondant.
- On choisit le rendement le plus avantageux de tous. S'il y a conflit entre deux rendements égaux, je pensais choisir la plus grande barre, mais ton raisonnement penche plutôt sur la petite.

**Inconvénients** :-1: 
1. Le fait de devoir changer l'algorithme et la structure du programme de manière non négligeable (ce n'est pas de la folie non plus...c'est tout à fait faisable...)
2. Les ressources utilisées sont plus importantes, puisque lors de la combinatoire, ne sachant pas encore à quelle barre on a affaire, on ne peut arrêter de combiner que dès que la somme des tronçons dépasse la longueur de la plus grande barre...

**Avantage** :+1: 
 Le fait d'arrêter notre choix sur une barre au début ne garantit pas du tout un algorithme optimisé : on risque en effet de caser des tronçons précieux pour un mauvais rendement sur cette barre alors qu'ils auraient fait un bon rendement sur une autre barre... Dans cet algorithme, on choisit le meilleur rendement en général, peu importe la barre, et je pense que ça doit donner de meilleurs résultats (sans en être sûre !)

Je propose deux possibilités : 
1. Nous nous mettons d'accord sur une des deux solutions, personnellement je suis ouverte aux deux, et je pourrais m'occuper des modifications.
2. Le monde de l'algorithmique qui s'ouvre un tout petit peu à nous maintenant est vraiment passionnant, et il semble que nous n'avons pas les outils théoriques nécessaires (quelqu'un les a-t-il ?) pour déterminer théoriquement quelle serait la meilleure solution. Que penses-tu de cette idée : chacun de nous deux forkera sa propre branche depuis le master, et codera un des deux algorithme, disons qu'on se donne une petite semaine, puis, nous confronterons les résultats en terme de temps de calcul et de rendement obtenu (banc d'essai). Nous choisirons alors la meilleure solution prouvée par l'expérience... Je pense que cette expérience serait extrêmement intéressante, et je suis aussi certaine que Gilles Bernard appréciera beaucoup l'idée. De plus, comme nous sommes deux, ce n'est pas trop lourd pour les nerfs de coder une solution qui marche, et de se casser encore la tête pour une solution meilleure...

Qu'en dis-tu ?

**Comment by ninja427** [comment]
Le 2015-04-30 10:20, rcharb1 a écrit :

> Oui, ça me paraît plausible comme algorithme... ça ne garantit pas LE
> résultat parfait, mais ça optimise quand même, et comme tu le dis, ça
> permet d'avoir des chutes réutilisables...
>  De mon côté, je pensais plutôt à un algorithme de ce type :
> - On effectue toutes les combinaisons possibles, sans encore savoir
>   à quelle barre chacune des combinaisons peut s'appliquer.
> - On "attache" ensuite à chaque combinaison la barre qui lui
>   convient le mieux et on calcule le rendement correspondant.
> - On choisit le rendement le plus avantageux de tous. S'il y a
>   conflit entre deux rendements égaux, je pensais choisir la plus 
>   grande
>   barre, mais ton raisonnement penche plutôt sur la petite.
> 
> INCONVÉNIENTS :
> 1. Le fait de devoir changer l'algorithme et la structure du
>    programme de manière non négligeable (ce n'est pas de la folie non
>    plus...c'est tout à fait faisable...)
> 2. Les ressources utilisées sont plus importantes, puisque lors de
>    la combinatoire, ne sachant pas encore à quelle barre on a affaire, 
>    on
>    ne peut arrêter de combiner que dès que la somme des tronçons dépasse
>    la longueur de la plus grande barre...
> 
> AVANTAGE
>  Le fait d'arrêter notre choix sur une barre au début ne garantit pas
> du tout un algorithme optimisé : on risque en effet de caser des
> tronçons précieux pour un mauvais rendement sur cette barre alors
> qu'ils auraient fait un bon rendement sur une autre barre... Dans cet
> algorithme, on choisit le meilleur rendement en général, peu importe
> la barre, et je pense que ça doit donner de meilleurs résultats (sans
> en être sûre !)
> 
> Je propose deux possibilités
> 1. Nous nous mettons d'accord sur une des deux solutions,
>    personnellement je suis ouverte aux deux, et je pourrais m'occuper 
>    des
>    modifications.
> 2. Le monde de l'algorithmique qui s'ouvre un tout petit peu à nous
>    maintenant est vraiment passionnant, et il semble que nous n'avons 
>    pas
>    les outils théoriques nécessaires (quelqu'un les a-t-il ?) pour
>    déterminer théoriquement quelle serait la meilleure solution. Que
>    penses-tu de cette idée : chacun de nous deux forkera sa propre
>    branche depuis le master, et codera un des deux algorithme, disons
>    qu'on se donne une petite semaine, puis, nous confronterons les
>    résultats en terme de temps de calcul et de rendement obtenu (banc
>    d'essai). Nous choisirons alors la meilleure solution prouvée par
>    l'expérience... Je pense que cette expérience serait extrêmement
>    intéressante, et je suis aussi certaine que Gilles Bernard appréciera
>    beaucoup l'idée. De plus, comme nous sommes deux, ce n'est pas trop
>    lourd pour les nerfs de coder une solution qui marche, et de se 
>    casser
>    encore la tête pour une solution meilleure...
> 
> Qu'en dis-tu ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] 
> https://github.com/pierre-H/optimiseur-coupe/issues/10#issuecomment-97704581

Ta solution a le mérite d'être astucieuse !
Comme quoi, on pense avoir envisagé toutes les possibilités, et une 
autre idée déboule.
Je pense que ta solution ne sera pas si gourmande que ça, et qu'elle 
sera meilleure.
Mais ça peut être sympa de tester les deux effectivement. As-tu une 
idée de définition pour le benchmark ?

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
Merci ! C'est l'avantage d'être à plusieurs avec chacun ses idées ! Vraiment ça fait du bien de pouvoir confronter son avis avec celui des autres quand on est dans des études par correspondance...
Tu veux dire qu'on rédige tout de suite le benchmark avant de commencer ? Qu'on mette tout de suite en place les différents tests et les critères selon lesquels on choisira l'une ou l'autre solution ? 
Du coup, c'est comme tu veux, si tu pense que cette solution est mieux, on peux aller directement dessus, mais si tu as les nerfs, le benchmark me dit beaucoup ! De mon côté, je commence le "chantier" pour cette modification.
Fais-moi savoir si tu veux te lancer dans le benchmark ou non !

**Comment by ninja427** [comment]
Le 2015-04-30 16:06, rcharb1 a écrit :

> Merci ! C'est l'avantage d'être à plusieurs avec chacun ses idées !
> Vraiment ça fait du bien de pouvoir confronter son avis avec celui 
> des
> autres quand on est dans des études par correspondance...
>  Tu veux dire qu'on rédige tout de suite le benchmark avant de
> commencer ? Qu'on mette tout de suite en place les différents tests 
> et
> les critères selon lesquels on choisira l'une ou l'autre solution ?
>  Du coup, c'est comme tu veux, si tu pense que cette solution est
> mieux, on peux aller directement dessus, mais si tu as les nerfs, le
> benchmark me dit beaucoup ! De mon côté, je commence le "chantier"
> pour cette modification.
>  Fais-moi savoir si tu veux te lancer dans le benchmark ou non !
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] 
> https://github.com/pierre-H/optimiseur-coupe/issues/10#issuecomment-97807935

Effectivement je pense que ça pourrait être mieux de définir des 
critères pertinents avant, autrement dit quels sont les worst cases à 
définir ? Et c'est là toute la difficulté, car comment piéger nos 
versions pour leur faire rendre gorge (que ce soit au niveau des 
performances ou de la qualité des résultats) ? Il est même probable que 
ce sera plus difficile que de rédiger les progs eux même. Je vais 
jusqu'à penser que définir ces critères pourrait nous amener à choisir 
une version avant même de l'avoir écrite... En substance on retombe sur 
ce que tu disais tout à l'heure quant aux outils théoriques 
nécessaires...
Pour conclure, je suis preneur si tu as des idées sur la définition de 
ces critères, car je vois que tu as déjà beaucoup réfléchi au problème 
et je m'attends à ce que tu me surprennes encore.

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
C'est vrai qu'il est mieux de réfléchir avant...
Pour ta solution, le worst case serait sûrement s'il y a des très bonnes combinaisons possibles pour certaines des barres, mais que tous les tronçons le permettant sont utilisés pour la première barre pour un rendement pas fameux.
ex :  3 barres de départ respectivement de 50 cm, 1m et 1m
on veut les tronçons suivants : 5cm,  90 cm, 90 cm.
Dans ce cas-là, le programme ferait l'absurdité de mettre les 5 cm dans la première barre de 50 cm parce qu'il ne peut pas faire mieux pour cette barre. Mais le pb est qu'ici, il n'avait même pas besoin de prendre en ligne de compte la première barre !
Pour ma solution, le pire des cas serait le cas de beaucoup de tronçons et beaucoup de barres avec une combinatoire qui monte en flèche, et il faudrait réussir à définir un seuil au dessus duquel l'activité du moteur utilise trop de ressources et de temps. Pourquoi ne pas fixer la limite à 2 ou 3 secondes de réponse (ça nous laisse une marge confortable, et ce n'est même pas sûr que ce soit pertinent, vu que c'est un programme qui ne s'utilise **qu'une fois** par opération de coupe... L'industriel peut bien patienter un peu, non ?)

As-tu plus d'idées sur d'autres paramètres du benchmark ? Sinon, je crois que tu as aison, que le fait de penser au pire  des cas nous aide peut-être à trouver la solution sans benchmark...

PS : penses-tu qu'il serait intéressant, avant de rendre le projet, ou même maintenant, de transférer ce genre de discussion sur le forum, histoire qu'ils voient qu'on a un peu réfléchi sur notre programme ?

**Comment by ninja427** [comment]
Le 2015-04-30 16:36, rcharb1 a écrit :

> C'est vrai qu'il est mieux de réfléchir avant...
>  Pour ta solution, le worst case serait sûrement s'il y a des très
> bonnes combinaisons possibles pour certaines des barres, mais que 
> tous
> les tronçons le permettant sont utilisés pour la première barre pour
> un rendement pas fameux.
>  ex : 3 barres de départ respectivement de 50 cm, 1m et 1m
>  on veut les tronçons suivants : 5cm, 90 cm, 90 cm.
>  Dans ce cas-là, le programme ferait l'absurdité de mettre les 5 cm
> dans la première barre de 50 cm parce qu'il ne peut pas faire mieux
> pour cette barre. Mais le pb est qu'ici, il n'avait même pas besoin 
> de
> prendre en ligne de compte la première barre !
>  Pour ma solution, le pire des cas serait le cas de beaucoup de
> tronçons et beaucoup de barres, et il faudrait réussir à définir un
> seuil au dessus duquel l'activité du moteur utilise trop de 
> ressources
> et de temps. Pourquoi ne pas fixer la limite à 2 ou 3 secondes de
> réponse (ça nous laisse une marge confortable, et ce n'est même pas
> sûr que ce soit pertinent, vu que c'est un programme qui ne s'utilise
> QU'UNE FOIS par opération de coupe... L'industriel peut bien 
> patienter
> un peu, non ?)
> 
> As-tu plus d'idées sur d'autres paramètres du benchmark ? Sinon, je
> crois que tu as aison, que le fait de penser au pire des cas nous 
> aide
> peut-être à trouver la solution sans benchmark...
> 
> PS : penses-tu qu'il serait intéressant, avant de rendre le projet, 
> ou
> même maintenant, de transférer ce genre de discussion sur le forum,
> histoire qu'ils voient qu'on a un peu réfléchi sur notre programme ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] 
> https://github.com/pierre-H/optimiseur-coupe/issues/10#issuecomment-97821672

Je savais que tu me surprendrais !
Tu viens de démontrer avec aisance qu'on ne peut pas retenir ma 
solution, ton exemple pointe du doigt un grave manquement.
Concernant le temps de réponse potentiellement long, c'est déjà 
"résolu" dans le document concernant la "gestion des erreurs / saisies" 
que je suis en train de rédiger. C'est "résolu" par la gestion des 
saisies aberrantes.
Concernant le forum, je pense que toute publicité est bonne à prendre 

## ;-)

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
Bon, et bien voilà qui est réglé ! Merci pour ta bonne idée de réfléchir un peu avant de  se lancer bêtement dans une entreprise inutile qui aurait  demandé du temps et de l'effort...
Je m'occupe donc de cette modification et je me donne, disons, une semaine pour ça.
Pourrais-tu t'occuper de mettre la "publicité" ;-)sur le forum ?
Bonne soirée !
Rébecca

**Comment by ninja427** [comment]
Pas de souci pour la pub !
Je le fais sitôt que j'ai fini le document concernant la "gestion des 
erreurs / saisies" (+ un devoir pour leque je ne trouve jamais le temps 

## de faire la mise au propre). Dans le weekend donc !

Cordialement,

Xavier JANIN.

Elève 12316706
