### ISSUE TITLE
Gestion des entrées

### ISSUE THREAD

**Issue by ninja427** [pierre-H/optimiseur-coupe#12]
Bonjour,

J'ai enfin fini la prose promise (fichiers Gestion_des_entrees.xxx).
Etant loin d'être omniscient, vos commentaires et propositions sont les bienvenus.
Si cela vous convient, je peux intégrer cette analyse dans le cahier des charges, et le compléter avec la gestion des sorties.

Bonne lecture !

**Comment by ninja427** [comment]
P.S. : N'hésitez pas à commenter le fichier lui même !

**Comment by pierre-H** [comment]
Ah génial !
Ce document va beaucoup m'aider !

**Comment by ninja427** [comment]
J'espère !

N'hésite pas à pointer les âneries !

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Question : **7.fichier de configuration** désigne un véritable fichier de configuration ?

**Comment by ninja427** [comment]
Oui en XML, mais avec 5 entrées uniquement, et ce n'est pas figé 
évidemment. On n'est pmême pas obligé d'en passer par là. En fait il 
suffirait de le parcourir au lancement du programme, pour définir les 
seuils en deça et au delà desquels on avertit l'utilisateur d'une 
possible erreur de saisie. Ou alors on décide de seuils immuables, mais 
c'est moins user friendly...
Encore une fois tout est discutable dans ce rapport, il ne s'agît que 
de suggestions.
L'idée est de le mettre dans le cahier des charges lorsqu'un consensus 
aura été trouvé.

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Quel est l'intérêt pour l'utilisateur d'enregistrer ces valeurs là pour plus tard ?

**Comment by ninja427** [comment]
Uniquement de pouvoir virer des warning à répétition pour un 
utilisateur qui utilise couramment des valeurs hors norme.

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Je me demande si il ne serait pas préférable de fixer des valeurs immuables parce que cela va ajouter de la complexité au programme juste pour gérer des cas extrêmement rares

**Comment by ninja427** [comment]
Je suis bien sûr ouvert à cette suggestion, le plus simple étant 
souvent le mieux, mais je ne sais pas comment justifier le choix des 
valeurs de seuil... Lorsque j'étais intérimaire chez Fermob, j'ai déjà 
personnellement fait des séries de 15000 découpes... Une solution 
intermédiaire pourrait être de garder un fichier xml éditable à la main, 
sans passer par le programme ? C'est très facile à parser à l'ouverture 
du programme, et ça permet à l'utilisateur de modifier des seuils 
(d'erreur et non plus de warning) en cas d'utilisation exotique.

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Je pense que si l'on retient la solution du xml, il vaut mieux créer une fenêtre configuration qui soit user friendly et permette la création automatique du xml.
Une solution serait que si le fichier config.xml existe, alors on l'utilise, sinon on utilise des valeurs par défaut.

**Comment by ninja427** [comment]
Mais du coup, ces valeurs, on les rend bloquantes, alors ? Moi je pense 
que c'est effectivement une bonne idée (ça simplifie le programme).
Un xml facultatif c'est bien aussi, ça simplifie l'install, j'aime bien 
l'idée :)

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
Très beau boulot Xavier !
Je n'ai eu le temps de bien regarder ton fichier que maintenant.
Je ne suis pas familière avec les notions de xml et fichier de configuration. Je vous laisse donc décider sur ce point.

**Comment by pierre-H** [comment]
Je peux m'occuper de la création de la fenêtre de configuration, la création et l'utilisation du fichier xml.

La question est : est-ce que l'on utilise un fichier de config pour gérer les cas extrêmes ou des valeurs immuables pour se simplifier le programme ?

**Comment by rcharb1** [comment]
Est-ce que le fait de créer un fichier de config compliquerait tellement le programme ?
Je veux dire par là que si une fonction utilise la variable epaisseurLameMax, qu'est ce que ça change dans le corps du programme, si cette valeur est fixée par défaut mais qu'elle est par ailleurs susceptible d'être modifiée ?

**Comment by ninja427** [comment]
Si cela vous convient, je modifie le fichier "Gestion des entrées" ce 
soir pour rendre toutes les évolutions plus claires.
Si j'ai bien compris, des valeurs limites seraient présentes en dur 
dans le code, mais pourraient être surchargées par d'autres valeurs 
présentes dans un fichier xml (créé par le programme lors de la première 
modification des valeurs seuils). Ces valeurs auraient un rôle de seuil 
non dérogeable, en cas de dépassement de l'un de ces seuils le moteur 
d'optimisation ne pourrait pas être lancé.
Est ce que j'ai tout bon ?

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
ça me semble très raisonnable, et je propose qu'on code toutes les fonctions de tests (à part le fichier xml) dans le fichier conversions.cpp déjà écrit, et qu'on pourrait renommer en saisies.cpp. En effet, il s'agit vraiment du même type de fonctions : les vérifications et conversions nécessaires **avant** le moteur pour ne pas l'embrouiller avec des tests nombreux et compliqués.

**Comment by ninja427** [comment]
C'est exactement l'idée de la démarche. J'ajoute qu'il reste encore un 
peu de travail de "préparation" avant codage, car il faut définir toutes 
les entrées / sorties avant de coder la boite noire au milieu...
Là, l'idée semble actuellement être de restituer les résultats sur une 
page distincte, avec possibilité de sauvegarde sous format html, mais 
quid des unités de restitution ? Il faut encore formaliser les sorties 
aussi (même si tout est quasiment fait), nous aurons ainsi un cahier des 
charges complet. C'est pourquoi je vous propose, une fois définitivement 
adoptée la gestion des entrées, de faire le même type de travail 
d'analyse vis à vis des sorties. C'est loin d'être trivial, et je suis 
d'accord pour faire le même type d'ébauche que celle déjà effectuée. 
Après nous serons en mesure de faire un schéma fonctionnel, de répartir 
les tâches, de faire un planning, même si tout a déjà été fait. En gros 
de donner un habillage, une ossature en vue de la soutenance, et d'être 
en mesure de justifier tous les choix effectués.
Etes-vous d'accord ?

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by ninja427** [comment]
Le 2015-05-05 09:58, Xavier JANIN a écrit :

> C'est exactement l'idée de la démarche. J'ajoute qu'il reste encore
> un peu de travail de "préparation" avant codage, car il faut définir
> toutes les entrées / sorties avant de coder la boite noire au
> milieu...
> Là, l'idée semble actuellement être de restituer les résultats sur
> une page distincte, avec possibilité de sauvegarde sous format html,
> mais quid des unités de restitution ? Il faut encore formaliser les
> sorties aussi (même si tout est quasiment fait), nous aurons ainsi un
> cahier des charges complet. C'est pourquoi je vous propose, une fois
> définitivement adoptée la gestion des entrées, de faire le même type
> de travail d'analyse vis à vis des sorties. C'est loin d'être 
> trivial,
> et je suis d'accord pour faire le même type d'ébauche que celle déjà
> effectuée. Après nous serons en mesure de faire un schéma 
> fonctionnel,
> de répartir les tâches, de faire un planning, même si tout a déjà été
> fait. En gros de donner un habillage, une ossature en vue de la
> soutenance, et d'être en mesure de justifier tous les choix 
> effectués.
> Etes-vous d'accord ?

Je me suis tellement emballé que j'en ai oublié la raison d'être de ce 
mail au départ...
En fait, le module dont tu parlais, Rebecca, c'est une excellente idée, 
mais peut-être pourrait-il être amené à changer en fonction des 
conversions de sortie ?

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Concernant la partie "**3. Types des champs de saisie**" je pense en effet que pour les unités une liste déroulante suffit largement. En revanche, pour longueur et quantité une liste déroulante n'est pas à mon avis une bonne solution, d'ailleurs ce n'est pas fait pour cela (une liste déroulante est user friendly lorsqu'il y a quelques valeurs mais quand il y a des dizaines voir des centaines de valeur, ce n'est vraiment pas pratique) : on devrait rester avec les spinbox qui font parfaitement l'affaire.

**Comment by ninja427** [comment]
Toutes mes plus plates excuses, je n'avais pas compris ce qu'était une 

## spinbox ! C'est parfait, c'est très exactement ce qu'il faut !

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Superbe !

**Comment by pierre-H** [comment]
Maintenant que j'ai codé la classe permettant de convertir à partir/ vers le mm, je propose que je code les 3 vérifications décrites dans le fichier de Xavier **Gestion_des_entrées** au paragraphe **4) Interactions entre les saisies**. Je propose que lorsqu'on clique sur le bouton _Appliquer_ un message d'erreur apparaît décrivant l'erreur.
Tout le monde est d'accord ?

(Note : la class ConvertUnit peut-être utilisée en dehors de Qt si quelqu'un en a besoin avec les méthodes ConvertUnit::toMm() et ConvertUnit::toUnit() )

**Comment by ninja427** [comment]
Pour moi c'est tout bon !

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
Parfait aussi pour moi !

**Comment by pierre-H** [comment]
J'ai ajouté la vérification et l'affichage des erreurs 4.b et 4.c que vous pouvez tester.
Concernant l'erreur 4.a, peux-tu @ninja427 m'expliquer la différence entre celle-ci et la 4.b et quel test doit être effectuée. J'ai du mal à la comprendre ... Merci !

**Comment by ninja427** [comment]
Bonjour, Pierre,

En fait Il ne fallait ajouter ani la 4a, ni la 4b, c'est expliqué dans 
"6 - synthèse". Car finalement il s'agît d'"erreurs" gérées par le 
moteur d'optimisation. Dans le paragraphe 4 on est encore en phase 
d'analyse. Pour répondre à tes interrogations, le 4a correspond au cas 
où les barres en entrée ne sont pas assez longues pour fournir les 
tronçons demandés. Tout ce laïus avait pour but :
- De vérifier et démontrer que toutes les erreurs relatives à la saisie 
  avaient été prises en compte
- De fournir une amorce d'analyse fonctionnelle (à compléter ensuite) 
  en vue de compléter le cahier des charges
- De préparer la soutenance

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Oui, mais c'est plus rapide/simple de faire la vérification avant de lancer le moteur. La vérification de 4.b et 4.c ne prennent que quelques lignes et je peux donc facilement afficher le message d'erreur, plutôt que d'attendre que le moteur me renvoie un message d'erreur.

**Comment by ninja427** [comment]
Si tu lis ce que j'ai écrit, tu verras qu'il y a une utilité à lancer 
le moteur... Et le moteur de Rebecca le gère déjà.

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Alors, j'ai mal compris le paragraphe 6. Désolé.

**Comment by pierre-H** [comment]
Du coup, que signifie les messages suivants pour que l'on soit sur la même longueur d'onde ?

@ninja427 : Pour moi c'est tout bon !
@rcharb1 : Parfait aussi pour moi !

**Comment by ninja427** [comment]
Tu as le droit de me traiter de nullité ambulante (voire même 
immobile). En fait ma réponse (trop hative) était focalisée sur "Je 
propose que lorsqu'on clique sur le bouton Appliquer un message d'erreur 
apparaît décrivant l'erreur.". J'aurais dû relire attentivement le 
paragraphe 4. Du coup il faut redemander à Rebecca maintenant...
Ne pas oublier que j'ai encore des modifications mineures à apporter à 
ce fichier suite à nos discussions.

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Oh non @ninja427, c'est moi qui comprend mal !
Au moins, ce travail m'a permis de découvrir une erreur dans mon code importante.
Je vais donc patienter jusqu'à ce que l'on soit d'accord au final.

**Comment by ninja427** [comment]
Ta patience à mon égard t'honore !

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
C'est gentil. Merci :)
