### ISSUE TITLE
Placement des résultats

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#13]
J'ai mis dans le dossier gui l'état actuel du programme. Je vous invite tous à compiler pour avoir un aperçu du résultat.
Ma question est la suivante : ne pensez-vous pas que mettre les résultats dans la même fenêtre ce n'est pas trop et qu'il vaut mieux ouvrir une deuxième fenêtre afin d'afficher les résultats (j'ai peur que le graphique prenne trop de place...) ?

**Comment by ninja427** [comment]
Le 2015-05-04 14:25, Pierre a écrit :

> J'ai mis dans le dossier gui l'état actuel du programme. Je vous
> invite tous à compiler pour avoir un aperçu du résultat.
>  Ma question est la suivante : ne pensez-vous pas que mettre les
> résultats dans la même fenêtre ce n'est pas trop et qu'il vaut mieux
> ouvrir une deuxième fenêtre afin d'afficher les résultats (j'ai peur
> que le graphique prenne trop de place...) ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] https://github.com/pierre-H/optimiseur-coupe/issues/13

Bonjour,

personnellement j'opterais plutôt pour une fenêtre unique pourvue d'un 
ascenseur, ça permet d'avoir la requête et le résultat sous les yeux, 

## mais je suis ouvert à une fenêtre indépendante.

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
C'est vrai que ce serait pratique de n'avoir qu'une seule fenêtre mais elle est déjà assez importante et devoir déplacer le graphique avec des ascenseurs, ce n'est pas pratique non plus.
Test le programme et dis moi ce que tu en penses.

**Comment by ninja427** [comment]
Je ne peux pas tester le programme au boulot :(
Je le fais ce soir !
Promis juré !

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Superbe :)
Bon courage !
