### ISSUE TITLE
Limite des champs

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#14]
Quelle limite maximale met-on aux champs : dimension, quantité et épaisseur de lame ?
Pour le moment, j'ai mis respectivement 999,99 - 999 - 99,99.
Je viens de me rendre compte qu'il est ridicule de mettre la valeur minimale du champ quantité à 0. Je vais la mettre à 1.

**Comment by ninja427** [comment]
Bonjour,

Dans le document "Gestion des entrées" que j'ai (enfin) mis sur le repo 
hier, il y a des préconisations concernant les limites. Pourrais-tu me 
faire un retour dessus ?

## Merci .

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Oui je viens de voir :) je n'ai pas eu le temps de retirer l'issue.
Ce qu'il faut prendre en compte, c'est que plus la limite maximale est grande, plus la spinbox augmente de longueur ce qui est une perte de place.
De plus, dépasser le milliard (même 1000) je ne pense pas que cela soit nécessaire. Les unités sont là pour simplifier ça justement.

**Comment by ninja427** [comment]
En fait quand je parle du milliard, ou des années lumière, je parle des 
bornages pour éviter les plantages systèmes (dépassement de capacité du 
type). Je démontre juste que cette hypothèse est hautement improbable.
Après je cherche juste à pointer du doigt qu'une spinbox pure impose 
des limites que l'on n'est pas capable de définir pour tous les 
utilisateurs. C'est pourquoi je parle d'un champ hybride, une spinbox 
avec des quantité de 1 à 10 par exemple, mais n'empêchant pas la saisie, 
par exemple pour saisir la valeur 20, si la valeur ne se trouve pas dans 
la liste.

## 

Cordialement,

Xavier JANIN.

Elève 12316706
