### ISSUE TITLE
Nom du champ "dimension"

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#15]
En général, dimension désigne largeur et longueur. Or là nous n'avons qu'une seule valeur. Ne vaudrait-il mieux pas utiliser soir largeur soit longueur ?

**Comment by ninja427** [comment]
Longueur c'est bien !

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Superbe. Je change.
