### ISSUE TITLE
Exporter les discussions sur le forum de l'IED pour augmenter notre visibilité

### ISSUE THREAD

**Issue by ninja427** [pierre-H/optimiseur-coupe#16]
Petit pense-bête pour ne pas oublier...

**Comment by pierre-H** [comment]
Quelqu'un a eu une confirmation concernant cela ? Est-ce obligatoire ?
Personnellement, je trouve que c'est plus pratique de travailler avec les issues de GitHub.

**Comment by rcharb1** [comment]
C'est vrai que c'est plus pratique ici, mais il n'est pas inutile de montrer un peu ce qu'on fait au fur et à mesure. Après tout, nous ne sommes pas notés uniquement sur le résultat, mais aussi sur notre organisation.
Si vous le voulez, je peux me charger d'être notre "attaché commercial" ;-) et de transférer nos discussions tous les quelques jours sur les forums.

**Comment by pierre-H** [comment]
Je ne suis pas contre le transfert des conversations sur le forum, mais le repository étant publique, le correcteur a déjà accès à nos conversations.

**Comment by rcharb1** [comment]
Encore faut-il qu'il vienne regarder...
