### ISSUE TITLE
Ouverture de du projet Qt

### ISSUE THREAD

**Issue by rcharb1** [pierre-H/optimiseur-coupe#17]
Bonjour,
J'ai du mal à ouvrir le projet Qt avec Qt Creator : 
J'obtiens le message Project ERROR: Unknown module(s) in QT: webkitwidgets.
Une idée du problème ?
Merci !

**Comment by pierre-H** [comment]
C'est dû à la ligne : 
QT += webkitwidgets
qui se trouve dans le fichier **OptimiseurDeCoupe.pro**
Cette ligne peut être supprimée pour l'instant mais on va en avoir besoin afin d'afficher le graphique des résultats si on le génère en html.

En attendant 2 solutions : 
1. supprimer la ligne
2. sudo apt-get install libqt5webkit5-dev

**Comment by rcharb1** [comment]
Ah ! ça y est, j'ai réussi !
C'est vraiment très bien !
J'aurais deux petites remarques : la valeur par défaut du champ "quantité" devrait être 1 et non 0, et je propose que l'unité par défaut soit plutôt le cm. Sinon, ça semble super !
De mon côté, j'ai rajouté la fonctionnalité des différentes tailles de barres initiales. Vous pouvez tester et me dire ce que vous en pensez, sachant que j'ai mis cette version sur un fork qui s'appelle Rebecca.
Bonne journée !

**Comment by pierre-H** [comment]
Merci.
Les modifs ont été faites et mises sur GitHub. J'ai aussi ajouté la classe ConvertUnit qui permet de convertir à partir ou vers le mm. Celui qui veut peut s'en servir. Je vais en avoir besoin pour la suite...

**Comment by pierre-H** [comment]
Rebecca, désolé ! Je n'avais pas vu ta fonction de conversion !
J'ai remarqué qu'elle ne va que dans un seul sens. Moi j'ai besoin des deux sens, je vais donc continuer à utiliser ma version.

**Comment by rcharb1** [comment]
Très bien, ce n'est pas grave, de toutes les façons, ce n'était pas un gros boulot !
Il faudra juste penser à faire le ménage de mes 2 fichiers conversion.
@pierre-H  @ninja427 : Pour ce qui est de l'ajout des barres initiales de tailles différentes, j'ai forké depuis la branche principale pour y mettre cette nouvelle version et je vais faire un pull request. 
Etant donné que cette modification a vraiment pas mal changé la structure du programme, que ce soit du point de vue des structures de données ou de l'algorithme, je préférerais que vous y jetiez un petit coup d'oeil avant de mettre cette modification sur la branche principale.
Bonne journée !

**Comment by pierre-H** [comment]
@rcharb1 ok, je vais regarder ça.
