### ISSUE TITLE
Double ou float ?

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#18]
Ayant remarqué que Rebecca utilise le type float, je me suis posé la question : doit-on vraiment l'utiliser.
Cette question est du au fait que les spinbox utilisés renvoient un nombre du type double.

Du coup, on a 2 choix : 
- soit on utilise que des double pour plus de précision
- soit on passe par une conversion lors de la récupération de la valeur.

[Pour plus d'infos concernant double vs float](https://programmers.stackexchange.com/questions/188721/when-do-you-use-float-and-when-do-you-use-double)

**Comment by ninja427** [comment]
Simplifier le programme en évitant les conversions me semble 
préférable, mais est ce que ça ne fera pas trop de travail à Rebecca 
pour faire les modifs ?

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Il suffirait de raire un Rechercher/Remplacer sur dans tout le dossier (Notepad++ ou gedit permet de faire cela)

**Comment by rcharb1** [comment]
oui, ce n`est pas une grosse histoire, je vais modifier ca. (desolee pour l`orthographe, clavier anglais...)

**Comment by pierre-H** [comment]
Superbe !
