### ISSUE TITLE
Explosion de la combinatoire

### ISSUE THREAD

**Issue by rcharb1** [pierre-H/optimiseur-coupe#19]
Bonjour,
Avez-vous fait un tour sur le [forum](http://foad.iedparis8.net/claroline/claroline/phpbb/viewtopic.php?cidReq=ELI421&gidReq=7&forum=60&topic=138&start=5) ? Qu en pensez-vous ? C est extremement vrai et ce serait dommage effectivement de bloquer lutilisateur alors qu on pourrait quand meme l`aider.

**Comment by ninja427** [comment]
Je suis entièrement d'accord avec toi. Maintenant on retombe plus ou 
moins sur ce dont on parlait lorsqu'on parlait des limites dans le 
fichier xml (les cas de plantage par dépassement de mémoire).
On a ouvert la boite de Pandorre... Qui aurait cru qu'on arriverait à 
ces niveaux de complexité avec un problème d'apparence aussi triviale ?
De mon côté, j'essaye de comprendre et de m'imprégner de tout ça, mais 
je pense que dans un premier temps un benchmark serait le bienvenu pour 
cerner les limitations de la version actuelle. Ca donnera des billes 
pour la suite, et pour la soutenance aussi. Ca fait partie des imprévus 
qui ne sont pas forcément décelables lors de l'établissement du cahier 
des charges !

## Le projet commence à avoir vraiment de la gueule... :)

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
En fait, je pense que le seuil est relativement facile a determiner : il semble que tout depende de la relation nb de troncon par barre. En effet, passer du simple au double du nombre de barres ne fait passer les calculs que du simple au double (complexite O (n)) alors que le fait de faire passer le nombre de troncons qu on peut rentrer par barre, du simple au double donne si je ne me trompe pas, O (n2) (lire carre). 
Il suffira donc de donner une limite a partir de laquelle le delai est insupportable, disons 5 secondes (mais on en discutera) puis on calcule le rapport LongueurMoyenneTroncons/LongueurMoyenneBarres, et on determine quelle est la limite inferieure a ne pas depasser de ce rapport. Une fois cette valeur determinee,  avant chaque lancement du programme, on calcule cette valeur et si elle est en dessous du seuil, il faudra faire basculer en mode heuristique dont il faut d ailleurs au on determine comment il va marcher...
Quand on croit qu on a fait la majeure partie !!!
Mais je suis d accord avec Xavier que c est interessant et que ca donne de la valeur au programme et nous donne un peu d experience...

**Comment by ninja427** [comment]
T'es trop forte !

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by ninja427** [comment]
Bon une excellente nouvelle, Gilles Bernard a visité notre forum !!!
Et ce qu'il en ressort :
Pas besoin de développer pour de vrai une approche heuristique, motif 
invoqué : on n'est qu'en deuxième année !
(Si j'ai bien compris)

## 

Cordialement,

Xavier JANIN.

Elève 12316706
