### ISSUE TITLE
Mettre à jour Cahier des charges

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#2]
objectif et timing : pourquoi pas fin max mi-juin ?
date de début : aujourd'hui
Les tailles en cm ?

**Comment by rcharb1** [comment]
ça me parît correct comme échéance

**Comment by rcharb1** [comment]
oui, les tailles en cm, désolée, j'avais oublié la question...

**Comment by pierre-H** [comment]
Ok
