### ISSUE TITLE
Mettre à jour le cahier des charges

### ISSUE THREAD

**Issue by rcharb1** [pierre-H/optimiseur-coupe#21]
Bonjour,
Je me permet de reciter le message de Gilles Bernard : 
"il me semble que le problème de départ n'est pas assez clairement décrit, que le cahier des charges n'est pas tout à fait au point, et que c'est un peu dangereux."
Il faut donc que l'un d'entre nous s'occupe de mettre à jour le cahier des charges...
Pouvons-nous en discuter (ce qu'il faut rajouter dans chaque catégorie, et quelles catégories ajouter etc...)
Une fois qu'on en aura discuté, ce sera très facile pour l'un d'entre nous de le mettre à jour !
Bonne journée !

**Comment by pierre-H** [comment]
Je propose que les modifications certaines, on les fait directement dans le fichier **Cahier des charges.md** (plus facile de modifier un document md pour que l'on puisse voir l'évolution, on le mettra à la fin en odt et pdf). Les autres modifs, on en discute directement ici.
