### ISSUE TITLE
Avancement des travaux, fixer date de réunion

### ISSUE THREAD

**Issue by rcharb1** [pierre-H/optimiseur-coupe#22]
Bonjour,
Je pense qu'il serait sage d'envisager une réunion comme celle de départ, le plus rapidement possible. En effet, pour éviter les "coups de bourre" de la fin et le stress qui va avec, il faut qu'on définisse tout ce qu'il reste à faire, qu'on se donne des échéances, et qu'on distribue les rôles restants. Nous devons penser à assembler les parties moteur et interface suffismment tôt pour avoir le temps de se retourner en cas d'imprévus. 
Il me paraît nécessaire que le programme soit prêt au moins une semaine avant la date, parce qu'il est quasiment certain qu'en testant alors sa robustesse, on trouvera de quoi redire et de quoi retoucher. Alors mieux vaut une semaine avant qu'un jour avant, non ?!
Il faudra aussi qu'on fixe une date pour la soutenance de projet et qu'on s'y prépare avec les conseils et l'expérience de nos prédecesseurs.
Je suis personnellement libre dimanche dans la matinée et dans la soirée à partir de 20h45. Quelles sont vos disponibilités ?
Bonne journée,
Rebecca

**Comment by pierre-H** [comment]
Excellente initiative. Je pense pouvoir être disponible dimanche à 20h45 mais cela n'est pas certain.
Je vais essayer de donner une réponse définitive aujourd'hui.

**Comment by rcharb1** [comment]
Merci ! on se tient donc au courant !

**Comment by pierre-H** [comment]
C'est ok pour dimanche à 20h45 pour moi.

**Comment by pierre-H** [comment]
Juste, le rdv se fait où ? Une issue de github ou le chat de notre groupe sur la platforme de l'IED ?

**Comment by ninja427** [comment]
## Bonjour à tous. OK pour moi dimanche à 20 h 45.

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
Je dirais plutôt le chat, mais je suis ouverte aux deux, c'est comme vous voulez.

**Comment by pierre-H** [comment]
Moi, pas de problème. J'espère qu'il fonctionnera bien cette fois.

**Comment by rcharb1** [comment]
D'accord, donc on fixe pour dimanche à 20 h 45 sur le chat. J'espère aussi qu'il fonctionnera bien !

**Comment by rcharb1** [comment]
rebonsoir

**Comment by ninja427** [comment]
J'y suis

**Comment by pierre-H** [comment]
hello :)

**Comment by ninja427** [comment]
Donc on parlait des valeurs de paramétrage

**Comment by pierre-H** [comment]
Oui, donc pour l'onglet paramétrage, si on utilise des spinbox, il faudra aussi une valeur de seuil. Or utiliser les valeurs maximales du type double me paraît beaucoup trop grand. Les unités sont là justement pour gagner en longueur.

**Comment by ninja427** [comment]
Bien vu

**Comment by pierre-H** [comment]
Donc, on fait quoi ?

**Comment by rcharb1** [comment]
je pense que pour la lame, les valeurs de Xavier sont bonnes

**Comment by ninja427** [comment]
Donc définir des valeurs max réellement aberrantes (par exemple 1 km pour les longueurs, 100000 pour les quantités, 10 cm pour l'épaisseur de lame) et des valeurs max par défaut de 2500 mm, 100 et 3 mm ?

**Comment by rcharb1** [comment]
et que pour la longueur des barres et des troncons, 20 m sont bien avec un seuil du rapport troncon/ barre moyen

**Comment by ninja427** [comment]
Je n'ai pas compris

**Comment by rcharb1** [comment]
Desolee, mal exprimee, je me rallie a ton idee sauf

**Comment by rcharb1** [comment]
pour ce qui est du rapport moyen troncon/barres qui ne pourra pas etre parametre

**Comment by rcharb1** [comment]
ou trs peu, parceque ca peut depasser la capacite de la machine

**Comment by ninja427** [comment]
Désolé je suis bouché : pourrais-tu donner un exemple ? stp

**Comment by rcharb1** [comment]
pour ce qui est detrouver cette valeur, je vais essayer de trouver

**Comment by rcharb1** [comment]
ok ;

**Comment by pierre-H** [comment]
Je commence à me perdre... Quand une conclusion a été trouvée concernant la valeur des seuils, faites moi signe. (est ce que cela implique aussi l'abandon du coup de l'onglet paramètre ?)

**Comment by rcharb1** [comment]
on a 15 barres de 10 m et on demande beaucoup beaucoup de tout petits morceaux. Le programme va s`emballer dans la cominatoire... Ce comportement est en grande partie determine par le rapport moyenne des longueurs de troncon / moyenne des longueurs des barres

**Comment by rcharb1** [comment]
et  c`est cette valeur qu`il faut fixer comme seuil et ne pas laisser l`utilisateur  parametrer sous peiune de se retrouver avec une machine a laver a la place d`un ordi

**Comment by rcharb1** [comment]
donc pour l onglet parametre qu on n abandonne pas, on propose a l utilisateur les valeurs seuil par defaut, qu il peut parametrer dans la limite du raisonable

**Comment by rcharb1** [comment]
raisonablequi est decrit par Xavier

**Comment by ninja427** [comment]
Ok là c'est clair
Mais peut-on considérer ça comme une erreur ? Car après tout c'est une demande légitime du client.
C'est délicat mais très bien vu de ta part, et finalement on peut effectivement fixer une limite pour les cas aberrants, qui est à définir, sachant que le client pourra surcharger cette valeur... C'est une bonne idée en fait. Pierre-Emmanuel, c'est bon pour toi ?

**Comment by pierre-H** [comment]
Peut-on faire un récapitulatif des valeurs de seuil par défaut, et celles qui définiront les champs dans l'onglet paramètre ?

**Comment by rcharb1** [comment]
seuil min troncon par defaut  ; 10mm
seuil max : 2500 mm
Seuil max par le parametrage : 20 000 mm
Seuil min par parametrage : 2 mm ?

**Comment by ninja427** [comment]
Les valeurs par défaut pourraient être les suivantes :
- Seuil longueur min : 10 mm pourrait être une valeur min plausible (parmi d'autres) (min 1 mm)
- Seuil longueur max : 2500 mm pourrait être une valeur max plausible (parmi d'autres) max 50 m
- Seuil quantité max : 100 pourrait être une valeur max plausible (parmi d'autres) max 25000
- Seuil épaisseur de lame max : le standard de l'épaisseur de lame (bois) est 3 mm, donc 4 mm est un bon candidat. (max 100 mm)

**Comment by ninja427** [comment]
Oui c'est bien aussi

**Comment by rcharb1** [comment]
on se rejoint, sauf 50 m pour toi au lieu de 20m, ce qui ne fait pas trop de difference

**Comment by pierre-H** [comment]
Ah, déjà j'y vois plus clair ! Merci ! :)
Les valeurs seront-elles les même pour les barres avant la découpe et les tronçons désirés ou elles sont différentes ?

**Comment by rcharb1** [comment]
je pense que ca peut etre la meme chose..

**Comment by ninja427** [comment]
Je pense pour ma part qu'on peut utiliser les mêmes
Après tout rien n'empêche de couper une barre de 2499 mm sur une barre de 2500 mm
Le souci pourrait se poser pour la longueur min

**Comment by ninja427** [comment]
En fait pour la longueur min le même raisonnement se tient

**Comment by rcharb1** [comment]
oui, meme pour le min, on peut se permettre la meme chose

**Comment by rcharb1** [comment]
Pour ce qui est du nombre maximal de troncons qu`on peut demander, je ne sais pas si on peut inventer facilement ce nombre. Je propose que Pierre-Emmanuel prepare un champ vide pour ca et qu`on le remplisse avec l`experience des tests du programme

**Comment by rcharb1** [comment]
Petit resume de ce dontnousavons parle jusque la :

**Comment by ninja427** [comment]
Il faut rajouter aussi le rapport moyenne tronçon / moyenne longueur

**Comment by rcharb1** [comment]
oui

**Comment by pierre-H** [comment]
(Note : je propose que l'on créé une nouvelle issue pour chaque nouveau sujet dont on discute ce soir pour pas que l'on se perd dans des dizaines de messages si l'on a besoin de les relire plus tard. Ok ?)

**Comment by rcharb1** [comment]
1. Cahier des charges par Xavier avec une super description des differents champs de l`interface. et une description des fonctionalites attendues

**Comment by rcharb1** [comment]
ou bien je peux faire commeladerniere fois de resumer dans un document la reunion

**Comment by ninja427** [comment]
Tu veux finir maintenant ?

**Comment by rcharb1** [comment]
1. Description du parametrage

**Comment by rcharb1** [comment]
je crois qu`on a encore quelques petites choses a discuter avant de terminer...

**Comment by ninja427** [comment]
Ouf

**Comment by rcharb1** [comment]
c`etait juste pour fixer les idees !!

**Comment by ninja427** [comment]
Pardon !
Promis je me tais et je te laisse finir !

**Comment by rcharb1** [comment]
1. Rajouter le traitement de la perte a la coupe

**Comment by rcharb1** [comment]
(le markdown me casse toute ma numerotation,lire 1 2 et 3)

**Comment by pierre-H** [comment]
@rcharb1 met tout dans un seul message
tu auras toute la numérotation

**Comment by rcharb1** [comment]
4Decouvrir les valeurs seuilsqu`on ne peut pas inventer

**Comment by rcharb1** [comment]
(mais bonjour l`attente !)

**Comment by rcharb1** [comment]
Je n`ai rien oublie pour l`instant c`est tout ?

**Comment by ninja427** [comment]
Oui c'est bon

**Comment by ninja427** [comment]
Je crois

**Comment by rcharb1** [comment]
Parlons maintenant d`un compte a rebours

**Comment by ninja427** [comment]
J'ai une question avant:
On fait une recherche heuristique en  cas de grandes valeurs ou pas ?

**Comment by rcharb1** [comment]
Je ne sais pas, vu que M. Bernard a un peu modere nos ardeurs sur le forum et qu`il faudrait inventer un nouvel algo...

**Comment by ninja427** [comment]
Je pense que ce n'est pas nécessaire effectivement

**Comment by rcharb1** [comment]
je suis pour abandonner cette idee a moins qu`on ne s`ennuie a la fin... ;-)

**Comment by ninja427** [comment]
OK pour moi

**Comment by pierre-H** [comment]
Ok

**Comment by rcharb1** [comment]
Pour pouvoir tester la robustesse du programme en entier, il faut deja avoir assemble les deux parties parce que la plupart des erreurs sont gerees par l interface. A quand l assemblage ?

**Comment by ninja427** [comment]
POur en finir avec le cahier des charges: il reste l'onglet restitution des résultats, et je vois que vous avez envie de passer à autre chose. Je vous fais une proposition plus tard et vous la commentez ? Ca vous convient ?

**Comment by rcharb1** [comment]
parfait ! sauf si tu veux en discuter maintenant !

**Comment by pierre-H** [comment]
Je pense que si on peut se mettre d'accord dès aujourd'hui sur certains points, alors autant le faure maintenant.

**Comment by ninja427** [comment]
OK

**Comment by rcharb1** [comment]
parfait, donc peut-on faire un affichage graphique avec un texte explicatif?

**Comment by ninja427** [comment]
Vous avez vu l'ébauche graphique que j'avais faite ?
Est ce que ça vous convient ?

**Comment by rcharb1** [comment]
pour moi, c`etait tres bien.

**Comment by ninja427** [comment]
Pas trop dur à faire, Pierre-Emmanuel ?

**Comment by pierre-H** [comment]
@ninja427 tu parles de ça https://github.com/pierre-H/optimiseur-coupe/blob/master/Exemple_fenetre_graphique.pdf ?
@rcharb1 **affichage graphique avec un texte explicatif** pour le cahier des charges ?

**Comment by ninja427** [comment]
Oui

**Comment by pierre-H** [comment]
@ninja427 : si l'image est mise à jour (onglets, paramètres ...) c'est ok pour moi.

**Comment by rcharb1** [comment]
disons que le cahier des chargesdemandera un schema de coupe graphique et une decription dutype morceau1 : 12cm, 56.5 cm 45.8 cm perte : 1 cm

**Comment by pierre-H** [comment]
ok, pour moi alors.

**Comment by ninja427** [comment]
OK j'ai donc une dernière question:
Par exemple on demande un tronçon de 50 mm, un de 2 inches et un autre de 3 cm, comment se passe la restitution ?

**Comment by rcharb1** [comment]
En graphique, un schema avec la legende de la longueur de chaque troncon represente avec son unite, et de meme en texte. Quel est le probleme ?

**Comment by ninja427** [comment]
Ok je voulais juste être sûr

**Comment by ninja427** [comment]
Donc on rajoute à tout ça la sauvegarde en html et c'est tout bon ?

**Comment by rcharb1** [comment]
@pierre-H d`autres details sur les resultats ?

**Comment by rcharb1** [comment]
Ah oui, les langues

**Comment by pierre-H** [comment]
Pour les résultats c'est ok. Il faut ajouter le bouton Enregistrer en HTML dans le cahier des charges.

**Comment by ninja427** [comment]
Les langues... Javais oublié...

**Comment by pierre-H** [comment]
Pour la traduction du programme, tout est déjà géré. J'ai pris en compte le français et l'anglais ce qui suffit je pense.

**Comment by ninja427** [comment]
Marvellous !

**Comment by ninja427** [comment]
Donc c'est bon pour le cahier des charges ?

**Comment by rcharb1** [comment]
amazing !

**Comment by rcharb1** [comment]
parfait pour moi

**Comment by ninja427** [comment]
Yiiiiahhhhh !!!!!

**Comment by rcharb1** [comment]
je propese que chacun annonce une date ou il pense pouvoir avoir fini son boulot.

**Comment by rcharb1** [comment]
Pour moi, demain, un manuel d`emploi du moteur pour Pierre-Emmanuel, et le resume de cette reunion. Pour la prise en charge de l epaisseur de la lame, fin de semaine

**Comment by pierre-H** [comment]
Pour ce qui est de la partie graphique, dans 2 jours tout sera bon à mon avis. Pour la génération du graphique dans les résultats, ça risque de prendre plus de temps car il faut que je m'habitue aux classes de dessin de Qt et aussi du temps pour la création de l'HTML (2 semaines pour ces deux choses max je pense)

**Comment by ninja427** [comment]
Alors... Pour moi il y a cahier des charges + analyse fonctionnelle. Dois je faire un manuel d'utilisation ?

**Comment by rcharb1** [comment]
Pourquoipqs, vu que celuique je vais donner a Pierre Emmanuel est seulement d usage interne

**Comment by ninja427** [comment]
Cahier des charges : milieu de semaine
Analyse fonctionnelle : début de semaine prochaine
Manuel d'utilisation : TBD

**Comment by ninja427** [comment]
Voyez-vous d'autres choses à rédiger ?

**Comment by rcharb1** [comment]
(voilq mon clqvier qui pqrle qnglqistout seul et lq touche espqce aui mqrche une fois sur deux !!

**Comment by rcharb1** [comment]
On avait aussi parle de la documentation il y a longteps, non ?

**Comment by rcharb1** [comment]
avec un document annexe des structures de donnees que je peux rediger

**Comment by ninja427** [comment]
Oui, tout à fait, pourriez-vous définir quelles sont vos attentes là dessus ?

**Comment by ninja427** [comment]
Oui tu es la mieux placée là dessus.

**Comment by ninja427** [comment]
Avez vous d'autres besoins ? Je peux prendre en charge d'autres choses.

**Comment by rcharb1** [comment]
Y a-t-il besoin d`un blabla personnel du type ''combien ce projet m`a apporte et quellesont ete les difficultes rencontrees'' etc ?

**Comment by pierre-H** [comment]
Oui, il y a un rapport perso que chacun doit rédiger dans son coin.

**Comment by rcharb1** [comment]
DOnc on a dit la doc pour toi Xavier ?

**Comment by ninja427** [comment]
Ca marche. Quels sont vos besoins ?

**Comment by rcharb1** [comment]
OK,donc ca c est personnel.

**Comment by rcharb1** [comment]
tu veux dire quel type de doc ?

**Comment by ninja427** [comment]
Oui

**Comment by ninja427** [comment]
Je peux aussi voir ce qui a été fait au niveau de la bataille navale et relire les préconisations de Gilles Bernard

**Comment by ninja427** [comment]
Je creuse ça de mon côté si vous voulez.

**Comment by rcharb1** [comment]
ca me parait bien de prendre exemple sur ce qui a dejaete fait, merci !

**Comment by ninja427** [comment]
Il faudra évidemment documenter toutes les fonctions.

**Comment by ninja427** [comment]
(C'est l'étape post fonctionnelle)

**Comment by rcharb1** [comment]
super, donc pour l`instant, ca nous amene  disons au 1er juin ou on met le programme ensemble pour le maltraiter du mieux qu`on peut et le rendre costaud

**Comment by ninja427** [comment]
OK pour moi

**Comment by pierre-H** [comment]
Ok pour moi aussi.

**Comment by rcharb1** [comment]
ce sera aussi la periode ou on devra se renseigner aupres de nos aines pour savoir a quoi s`attendre de l`entrevue

**Comment by pierre-H** [comment]
ok.

**Comment by ninja427** [comment]
Si je peux me permettre un commentaire à la con, je pense qu'il vaudra mieux s'adresser à Josué parmi les tuteurs.

**Comment by rcharb1** [comment]
Est-ce  que vous estimez necessaire qu je redige un resume de la reunion de c soir ?

**Comment by rcharb1** [comment]
oui, on lui demandera

**Comment by ninja427** [comment]
Pour moi c'est bon j'ai toutes les infos, je vais pouvoir avancer

**Comment by pierre-H** [comment]
Oui, bonne idée pour le tuteur. Pourquoi pas pour le résumé.  Y a t'il autre chose ? Pour moi, tout est ok

**Comment by pierre-H** [comment]
Je suis désolé, je dois vous laisser. Je suis content de l'avancé. Bravo à tout le monde. Bonne soirée !!!

**Comment by rcharb1** [comment]
pour moi aussi tout est ok, d`acord pour le resume ! C` etait une reunion bien utile, merci  et bonne nuit !

**Comment by ninja427** [comment]
Merci beaucoup !!! Et bonne soirée !
