### ISSUE TITLE
Valeurs de seuil

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#24]
Bonjour,
Je reviens sur les valeurs de seuil. On a défini qu'elles seraient les suivantes : 
- Seuil longueur min : 10 mm pourrait être une valeur min plausible (parmi d'autres) (min 1 mm)
- Seuil longueur max : 2500 mm pourrait être une valeur max plausible (parmi d'autres) max 50 m
- Seuil quantité max : 100 pourrait être une valeur max plausible (parmi d'autres) max 25000
- Seuil épaisseur de lame max : le standard de l'épaisseur de lame (bois) est 3 mm, donc 4 mm est un bon candidat. (max 100 mm)

Aujourd'hui, les valeurs maximales sont : 
- longueur : 999,99 (m/cm/mm/inches/yard/feets)
- quantité : 999
- epaisseur de lame : 99,99 (mm/inches)

Pourquoi ne pas abandonner l'onglet paramètre et laisser les valeurs maximales ainsi ?
(Pour mettre 2500 mm, il suffira de mettre 2,5 m etc).
Et pourquoi ne pas mettre pour la quantité 99 999 tout simplement ?
(J'essaye de simplifier l'utilisation du programme...)

**Comment by rcharb1** [comment]
Je pense qu'il est tout de même important qu'il y ait une différene entre l'utilisation habituelle du programme où il est rapide, silencieux et non envahissant, mais de laisser l'utilisateur choisir de vouloir faire travailler sa machine un peu plus dur en lui demandant des choses plus rares... Non ?

**Comment by pierre-H** [comment]
Changer les valeurs maximales n'a qu'un impact très minuscule sur la gui et aucun sur le moteur puisque celui ne reçoit que les valeurs envoyés par l'utilisateur. Alors, pourquoi s’embêter ?

**Comment by ninja427** [comment]
Si il y a un impact sur le moteur : lorsque les valeurs sont très 
élevées et que le temps de calcul en est impacté. Ce paramétrage est 
nécessaire pour utiliser des valeurs un peu moins plausibles mais pas 
impossibles pouvant impacter le fonctionnement du moteur (un message du 
genre "Changer ces valeurs peut conduire à un ralentissement voire une 
instabilité du programme" serait le bienvenu dans l'onglet paramétrage).

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Tu parles des valeurs **envoyées** par l'utilisateur, pas les valeurs maximales, n'est-ce-pas ?
Si, on donne la possibilité technique à l'utilisateur d'atteindre ces valeurs (en passant par l'onglet paramètre ou directement disponible), donc de toutes les façons il faudra passer par là.

J'ai l'impression qu'il y a 2 cas : 
* **A.** la valeur de seuil est de 999 999
* **B.** la valeur de seuil est de 999 mais en passant par l'onglet paramètre, on peut la mettre à 999 999

Dans les 2 cas, envoyer la valeur 75 (par ex.) prendra le même temps de calcul, de même que 364 ou 150 514 : le temps de calcul sera le même quelque soit le cas A ou B. Alors du coup, je ne comprend pas l'intérêt de l'onglet Paramètre, si ce n'est que ça ajoute des clics pour l'utilisateur qui en demande le moins possible et du code pour le développeur qui ... :-)

**Comment by pierre-H** [comment]
Tu parles des valeurs **envoyées** par l'utilisateur, pas les valeurs maximales, n'est-ce-pas ?
Si, on donne la possibilité technique à l'utilisateur d'atteindre ces valeurs (en passant par l'onglet paramètre ou directement disponible), donc de toutes les façons il faudra passer par là.

J'ai l'impression qu'il y a 2 cas : 
- **A.** la valeur de seuil est de 999 999
- **B.** la valeur de seuil est de 999 mais en passant par l'onglet paramètre, on peut la mettre à 999 999

Dans les 2 cas, envoyer la valeur 75 (par ex.) prendra le même temps de calcul, de même que 364 ou 150 514 : le temps de calcul sera le même quelque soit le cas A ou B. Alors du coup, je ne comprend pas l'intérêt de l'onglet Paramètre, si ce n'est que ça ajoute des clics pour l'utilisateur qui en demande le moins possible et du code. Mais rien de pratique en apparence.

Je me trompe ?

**Comment by pierre-H** [comment]
Note : Doit-on mettre un nombre de saisies maximum (pas quantité mais saisie qui inclut longueur-unité-quantité) ?

**Comment by ninja427** [comment]
Que fait-on alors ? Le problème de justifier le choix des valeurs extrêmes demeure... On peut arguer encore une fois du fait que l'on est en licence et faire l'impasse sur l'onglet paramètres, mais je ne vois toujours pas comment justifier le choix des valeurs extrêmes...

**Comment by pierre-H** [comment]
Personnellement, je pense qu'il faut rester sur les valeurs : 
- longueur : 999,99 (m/cm/mm/inches/yard/
- quantité : 999
- epaisseur de lame : 99,99 (mm/inches)

**Comment by ninja427** [comment]
Le 2015-05-31 16:11, Pierre a écrit :

> Personnellement, je pense qu'il faut rester sur les valeurs :
> - longueur : 999,99 (m/cm/mm/inches/yard/
> - quantité : 999
> - epaisseur de lame : 99,99 (mm/inches)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1]
> 
> https://github.com/pierre-H/optimiseur-coupe/issues/24#issuecomment-107191886

Peut-on changer les valeurs de seuil en fonction de l'unité ?
Parce qu'en fait 999,99 mm, ça ne fait jamais qu'un mêtre...

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Oui c'est possible, mais le cas 999,99 mm en soit n'est pas si méchant que cela et que si un utilisateur souhaite utiliser cette notation (53mm) au lieu de la simplifiée (5,3cm) autant lui laissé cette possibilité.
Si @rcharb1 et toi tenez vraiment a faire cela, indiquez-moi les valeurs maximales en fonction des unités.

**Comment by ninja427** [comment]
Le 2015-06-03 23:41, Pierre a écrit :

> Oui c'est possible, mais le cas 999,99 mm en soit n'est pas si
> méchant que cela et que si un utilisateur souhaite utiliser cette
> notation (53mm) au lieu de la simplifiée (5,3cm) autant lui laissé
> cette possibilité.
>  Si @rcharb1 [1] et toi tenez vraiment a faire cela, indiquez-moi les
> valeurs maximales en fonction des unités.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [2].
> 
>   *
> 
> ## Links:
> 
> [1] https://github.com/rcharb1
> [2]
> 
> https://github.com/pierre-H/optimiseur-coupe/issues/24#issuecomment-108623846

Autre solution : autoriser uniquement deux unités, le mm et l'inch et 
mettre le maximum à 9999,99.

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by ninja427** [comment]
Bon il faut absolument que j'avance donc pour l'instant dans le cahier des charges je mets:
longueur : 9999,99 mm
quantité : 999
epaisseur de lame : 99,99 mm

**Comment by pierre-H** [comment]
Autoriser 2 unités seulement je trouve cela dommage car cela donne moins de liberté à l'utilisateur : si c'est plus agréable pour lui de travailler en cm ou en yard, autant lui laisser cette possibilité. De toutes les façons point de vue technique ça ne change pas grand chose et c'est déjà mis en place, alors je propose (encore) qu'on laisse les choses ainsi : 
- longueur : 999,99 (m/cm/mm/inches/yard/feet)
- quantité : 999
- epaisseur de lame : 99,99 (mm/inches)

**Comment by rcharb1** [comment]
Désolée de mon silence...
D'abord, je voudrais remercier @ninja427 pour ce très beau cahier des charges. Bravo de s'être tout de suite mis au travail malgré un événement plutôt traumatisant...
Ensuite, je me permets de donner mon avis sur cette question (il faut garder en tête qu'il ne s'agit pas de quelque chose de si primordial dans le programme...)
Que pensez-vous de garder toutes les unités que l'utilisateur a le choix d'utiliser, mais de n'examiner les limites des champs, qu'une fois les conversions vers le mm effectuées ? ça permettrait d'avoir une limite unique, par exemple 9999.99 mm, tout en gardant pour l'utilisateur la souplesse du changement d'unité ? Je crois comprendre que c'est ce qu'a fait Xavier, non ?

**Comment by ninja427** [comment]
Tout à fait ! J'essaye de me placer dun point de vue utilisateur... Je pense que c'est là où je suis le plus utile sur ce projet.
Concernant le cahier des charges, il faut encore que j'étoffe la fin, le planning notamment, mais je vous avais déjà tellement fait attendre pour quelque chose qui devrait être acté avant même la première ligne de code. 
Avez-vous des modifications à suggérer ? J'ai simplifié au maximum la validation des saisies, mais j'ai la sensation d'avoir oublié des trucs...
Merci en tout cas pour la gentillesse de tes commentaires Rebecca !
