### ISSUE TITLE
Moteur Debug

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#25]
@rcharb1 je propose que dans le moteur, tu utilises des #if DEBUG et #endif dans le programme pour les affichages vers cout pour que l'on puisse travailler dans les mêmes fichiers sans que l'on combine cout et la gui. Exemple : 

```
du code sans cout...
#if DEBUB
cout << "Le résultat est " << result << endl;
#endif
du code sans cout...
```

Ainsi, tu pourras toujours travailler sur le moteur en mode console et moi en combinant le moteur et la gui, je n'aurai pas à compiler cout.
Qu'en dis-tu ?

**Comment by rcharb1** [comment]
OK, bonne idée !

**Comment by rcharb1** [comment]
Sachant que pour la version à rendre, on peut tout simplement les supprimer, non ?

**Comment by pierre-H** [comment]
Oui, mais tant que chacun travaille différemment sur le même code, je pense que c'est plus pratique avec cette solution.
