### ISSUE TITLE
Manuel d'utilisation

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#26]
@rcharb1, j'ai lu le manuel d'utilisation, ça m'aide bien : merci beaucoup.
Je crois qu'il va falloir faire quelques modificatifs. J'insiste car il est certain que l'on sera noté là-dessus car notre programme utilise peu le système [MVC](https://fr.wikipedia.org/wiki/Mod%C3%A8le-vue-contr%C3%B4leur) sans la partie modèle, or dans un travail d'équipe, très souvent ces trois parties sont réparties entre plusieurs personnes/équipes. L'équipe qui regroupe le tout doit savoir comment utiliser basiquement une partie sans en comprendre le fonctionnement, cela via une doc : ce que tu as fait. Ce projet ayant pour principal but de nous apprendre comment développer en équipe, ce point là est donc très important.
Du coup, je pense qu'il faudrait beaucoup plus simplifier le manuel et aller plus vers le concret.
**Exemple :**
Lancement du moteur : créer un objet DoubleListPaires dont le constructeur doit prendre en argument 2 List que l'on peut créer à partir de la fonction createSortedList etc...
Pour accéder aux résultats : appeler la méthode ??? l'objet DoubleListPaires etc...

Vois-tu où je veux en venir ? Je pense que le manuel doit aller droit à l’essentiel avec dans l'idée quelle est destinée à une personne n'ayant, disons, pas accès au code du moteur (et du coup, dans le manuel pas de code source à mettre, juste les noms des classes, méthodes et fonctions à utiliser).

Merci beaucoup !

----- Rien à voir -----
Sinon, une petite question concernant la classe DoubeListePaires : ne serait-il pas plus logique de l'appeler moteurCalcul par

**Comment by rcharb1** [comment]
Je comprends très bien ce que tu veux dire, et c'est effectivement un point très important.
Lorsque j'ai dû rédiger ce document, je me suis dit qu'il serait peut-être un peu trop abstrait de dire rien que des noms de fonctions et de classes et j'ai décidé de joindre aussi le code sources de ces fonctions à modifier, mais c'est vrai que ça n'a pas grand chose à faire dans un manuel de ce type...

Maintenant, comment est-ce que je devrais faire, parce que tu es obligé de redéfinir toutes les fonctions affiche par toi-même, non ? Donc je te donne la liste de toutes les fonctions à modifier ?

Pour ce qui est de DoubleListPaires, c'est vrai qu'il serait temps de changer le nom qui vient d'une vieille constructions de noms : Paire, ListPaires, puis DoubleListPaires. Entre temps j'ai renommé la classe ListPaires en Combinaison qui décrit mieux le rôle de la classe, mais la classe doubleListPaires regroupe tellement de choses que j'avais du mal à trouver un nom plus parlant ! j'adopte moteurCalcul avec soulagement !

Merci pour cette mise au clair !

**Comment by pierre-H** [comment]
Pour les fonctions d'affichage, je vais me débrouiller. Ce dont j'ai besoin, c'est uniquement d'**accéder** aux résultats. Exemple (ridicule peut-être) : 
moteurCalcul.resultat() renvoie [5.36, 3.2, 1.1]
Ce que je veux dire est que j'ai juste besoin des données brutes des résultats. Les fonctions d'affichage déjà créée peuvent être intégrée dans les conditions #if DEBUG pour les tests, mais j'en ai pas personnellement besoin.
D'autres classes s'occuperont de l'affichage des résultats. Pour moi, la classe moteurCalcul doit rester un simple moteur de calcul, et ne doit rien afficher.
Merci :)

**Comment by rcharb1** [comment]
Mais TOUT est dans DoubleListPaires heu... moteurCalcul
Donc en gros, j'envoie juste tout l'objet DoubleListPaires qui contient toutes les informations nécessaires, mais il faut aussi que je t'explique quoi faire avec, non ? ça suffisait l'explication des différents attributs de cette classe ?

**Comment by pierre-H** [comment]
Oui en effet. Dans ma tête, c'était clair que le moteur n'avait pour fonctions que de prendre des données brutes pour en ressortir d'autres (un moteur de calcul quoi :) ).

**Comment by rcharb1** [comment]
Désolée, je n'ai pas très bien compris le sens de ce "en effet". Est-ce que les explications que j'ai données sur la structure de donnée moteurCalcul sont suffisantes pour s'en servir ?

**Comment by pierre-H** [comment]
Elles le sont techniquement, mais il faudrait modifier la forme et simplifier la chose. Exemple : 
moteurCalcul.resultatFinal() renvoie une List contenant le résultat final.

Il faut vraiment que le document (que l'on présentera) soit simplifié un maximum et ne soit pas mis sous forme de code source mais d'un véritable manuel.

**Comment by rcharb1** [comment]
Je comprends, je vais corriger ça ce soir ou demain matin

**Comment by pierre-H** [comment]
Superbe ! Merci !

**Comment by pierre-H** [comment]
J'ai vu les modifs que tu as fait @rcharb1. C'est beaucoup mieux ! Merci !
Je me suis permis de modifier la première partie : Lancement du moteur.
J'ai remarqué que le manuel contient des références à des attributs de la classe MoteurCalculs, ne sont-ils pas privés ? Si oui, il vaut mieux alors parler des fonctions accesseurs plutôt que des attributs.
Merci en tout cas pour le travail fait.

**Comment by rcharb1** [comment]
Oui, c'est juste, ils sont privés... J'ai eu l'habitude de les manipuler à l'intérieur même de la classe, mais c'est vrai que depuis l'extérieur on a besoin des accesseurs... Good point !

**Comment by rcharb1** [comment]
Je vais rajouter ça. Merci pour l'organisation du répertoire de travail, c'est drôlement plus propre !

**Comment by pierre-H** [comment]
Avec plaisir :-) : au moins on s'y retrouve un peu plus.

**Comment by pierre-H** [comment]
Merci beaucoup pour la correction. C'est déjà beaucoup mieux !
Je me suis permit de simplifier les résultats 1 et 2.
Concernant le n°3, getResultatFinal, il faudrait aussi le simplifier mais apparemment c'est de type std::list mais une liste de quoi ? (int, char ... ?)

Concernant le texte : 

> Pour gérer l'affichage, il faudra donc adapter les fonctions suivantes :
> 1. La fonction affiche de la classe Combinaison, qui affiche toutes les informations relatives à une combinaison, à savoir les tronçons utilisés dans cette combinaison, à quelle taille de barre cette combinaison s'applique, et le rendement de coupe sur cette barre
> 2. La fonction affiche de la classe moteurCalcul qui est censé afficher les résutats finaux.
> 3. La fonction affiche de la classe List qui va servir à afficher les barres inutilisées à la fin, ou les troncons restants qu'on n'a pas réusii à couper par manque de matière première.

Est-il vraiment nécessaire ? Normalement il n'y a pas de fonctions à adapter : la gui récupère les résultats brutes et ce débrouille. Pas de fonction d'affichage à adapter dans le moteur normalement.

**Comment by rcharb1** [comment]
Dans le 3, il s'agit d'une liste d'objets Combinaison, objet qui est lui même composé d'une liste d'objets Paire, d'une barre à laquelle s'applique la combinaison et du rendement de la combinaison...

Je suis bien consciente du fait que la partie GUI n'a pas à s'occuper des structures de données du moteur, mais j'ai du mal à comprendre comment livrer à l'interface des données si complexes de manière "brute"... Il s'agit de données organisées : "dans telle barre, on a placé tels tronçons, ce qui donne le rendement tel", et ceci multiplié par le nombre de barres que l'on possède...

Vous voyez ici un moyen de renvoyer des données brutes ?

**Comment by rcharb1** [comment]
Je formule ma question plus précisément : qu'attend l'interface comme type de données pour afficher les résultats ?

**Comment by rcharb1** [comment]
Quand je parlais d'adapter les fonctions d'affichage, ce que je voulais dire c'est qu'elles constituent en elles-même un **excellent** mode d'emploi pour accéder aux différents champs des structures de données que reçoit l'interface et qui sont pertinents pour l'affichage.

**Comment by pierre-H** [comment]
J'ai passé tout ça dans le [Wiki](https://github.com/pierre-H/optimiseur-coupe/wiki/Manuel-d%27utilisation-du-moteur-de-calcul) avec des liens pour que les structures de données soient plus faciles d'accès.
Je vais modifier encore pas mal de trucs en m'aidant des fonctions affiche(). Regarde un peu ce que j'ai fait, si tu vois des modifs à faire : n'hésite pas. J'espère que tu comprendras où je veux en venir. (Note : je ne vais mettre que ce dont la gui a besoin dans la doc. Rien de plus.
