### ISSUE TITLE
Librairie Standard ou Qt ?

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#28]
Voilà une question assez technique :
Il existe la stl (std::) qui contient string, vector et List. Avec Qt, on a l'équivalent : QString, QVector et QList ([+infos](http://doc.qt.io/qt-5/containers.html)).
Il y a [un article](http://blog.codeimproved.net/posts/qtl-stl.html) très intéressant qui compare les deux librairies. Personnellement, j'ai jusque là utilisé la librairie de Qt. @rcharb1 a utilisé la stl.
Question : pensez-vous qu'il faut que l'on convertisse l'une des deux parties vers l'une des deux librairie ?

Mon avis sur la question est que l'on devrait tester le passage de tout le code vers la librairie de Qt pour que le code soit harmonieux (l'utilisation des deux librairies apparemment peut causer quelques problèmes). Mon choix vers Qt et non la stl est que on doit de toutes les façons utiliser Qt, alors autant aller jusqu'au bout.

Qu'en pensez-vous ?

**Comment by pierre-H** [comment]
(Il est possible que le passage d'une librairie vers une autre cause aussi des problèmes, ou que des fonctions utilisés par @rcharb1 ne soit pas dispo dans la qtl. C'est pour cela que je parle de **tester** le passage).

**Comment by rcharb1** [comment]
Désolée pour le délai de réponse...Oui, il semble qu'on va devoir changer de librairie pour le moteur, ou au moins essayer. J'espère que ça ne posera pas trop de problèmes. Je n'ai pas encore eu le temps de lire l'article. Pour l'instant, je suis en train de m'occuper du paramètre de la perte à la coupe, on se recontactera à ce propos.
Merci d'avoir souligné ce point !

**Comment by rcharb1** [comment]
A bien y réfléchir, ne pourrait-on pas se reposer sur [cette discussion](http://stackoverflow.com/questions/16082803/is-it-possible-to-have-existing-c-code-work-with-qt) et [cette autre](http://stackoverflow.com/questions/1349375/qt-ui-for-existing-c-project) pour décider d'utiliser les conteneurs tels qu'il sont ?
Tous les changer me paraît quand même un travail non négligeable, et il ne semble pas que ça pose finalement un tel problème d'utiliser une bibliothèque différente pour l'interface et pour le moteur...
Qu'en pensez-vous ?

**Comment by pierre-H** [comment]
Une solution serait de tester le mixage des 2 bibliothèques et voir le résultat.
Si cela fonctionne, alors on passe à la suite, sinon on passe vers la bibliothèque de Qt.

**Comment by rcharb1** [comment]
Faisons ça, si je dois le faire, je préfère le faire en sachant que c'est nécessaire ! Merci !

**Comment by pierre-H** [comment]
Après quelques tests, j'ai l'impression que la combinaison entre les 2 bibliothèques fonctionne correctement... On verra la suite...

**Comment by pierre-H** [comment]
Après quelques modifs, le programme n'utilise plus std::vector mais QVector que ce soit dans la GUI ou dans le moteur. Cela fait une harmonisation supplémentaire et facile.
