### ISSUE TITLE
Etude sur le rajout du paramètre perte à la coupe

### ISSUE THREAD

**Issue by rcharb1** [pierre-H/optimiseur-coupe#29]
Voila une petite étude sur le paramètre de perte à la coupe, si vous avez des choses à rajouter sur le raisonnement, n'hésitez pas, c'est pour ça que j'ai écrit le document !
Il semble vraiment que ça n'entraîne aucune modification majeure dans le programme.

Soit p la perte par coupe, deux cas de figures se présentent : 
1. S'il y a une combinaison pour une certaine barre, de telle sorte à ce qu'il n'y ait pas de chutes, on pert en tout, p \* nombre_de_troncons_dans_la_barre - 1
2. Si on a des pertes, il y aura une coupe en plus, c'est à dire p \* nb_de_troncons_dans_la_barre

Ainsi, il est très facile de rajouter à chaque tronçon la longueur p, avant de commencer les calculs. Mais comment traiter le cas du dernier tronçon d'une combinaison à 100% qui n'a pas de perte dûe à la coupe, lui ?
Il suffit, lors de chaque combinaison, de vérifier si somme_des_tronçons_de_la_combinaison = longueur_barre + p, ce qui voudrait dire que la combinaison est parfaite et qu'il y aura une coupe en moins à faire.

Au moment de la restitution des résultats, ou même plutôt au moment de la rentrée d'une combinaison valide dans la liste des combinaisons finales, on retranche de nouveau à chaque tronçon la valeur p.

L'important sera de ne pas s'embrouiller entre les valeurs de tronçons **avec** la perte, et celles **sans** la perte, mais bon, ça c'est de la technique... Ici, je voulais juste discuter de la validité du raisonnement.

**Comment by ninja427** [comment]
Parfait !
