### ISSUE TITLE
Ajout dynamique de champs

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#3]
Voulez-vous que l'on fasse un ajout dynamique de champs par rapport à la question **de combien de pièces disposez-vous ?** et la question **veuillez entrer les tailles des morceaux que vous voulez obtenir, séparés par des virgules** ?
Exemple
![Image Exemple 1](https://lut.im/U0Llik63/fnZeUQm9)
![Image Exemple 2](https://lut.im/eIBPo0or/BoW0GO0h)

**Comment by rcharb1** [comment]
Si ce n'est pas plus compliqué, pourquoi pas !
