### ISSUE TITLE
Etat des lieux ?

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#30]
Bonjour,
Je propose que l'on fasse un petit état des lieux ?

Personnellement, pour la Gui je pense avoir fait le maximum là : 
![image gui](https://camo.githubusercontent.com/8057618f9ba7cdc689b36860b3238edcd1f34d71/687474703a2f2f692e696d6775722e636f6d2f4b6552523679352e706e67)

Quelqu'un a t-il une remarque à faire ?

On avait fixé le 1er juin pour le rassemblement entre le moteur et la gui, donc la semaine prochaine. Est-ce qu'il y a d'autres étapes chez chacun à faire avant de pouvoir passer à celle-ci ?
Qu'en est-il du cahier des charges et du manuel d'utilisation ?

Bonne journée !

**Comment by rcharb1** [comment]
Bravo !
De mon côté, je crois que j'ai fait ce qu'on avait décidé que je fasse. Entre temps, il y a eu cette histoire de bibliothèque à changer, je vais essayer de m'en occuper cette après-midi.

**Comment by pierre-H** [comment]
@rcharb1 pourras-tu mettre à jour le manuel d'utilisation, surtout le paragraphe [Affichage des résultats](https://github.com/pierre-H/optimiseur-coupe/blob/master/Doc/manuel%20d%27utilisation%20sommaire.md#affichage-des-r%C3%A9sultats-) (le simplifier comme le 1er paragraphe et utiliser les noms des méthodes, pas des attributs).
Merci !

**Comment by rcharb1** [comment]
C'est incroyable, c'est exactement ce que je suis en train de faire, ainsi que de mettre à jour l'explication des structures de données ! Dès que j'aurai fini, je l'envoie !

**Comment by pierre-H** [comment]
Superbe ! Merci beaucoup !

**Comment by rcharb1** [comment]
@pierre-H c'est fait ! C'est mieux ?

**Comment by pierre-H** [comment]
@rcharb1 où ça ?

**Comment by rcharb1** [comment]
Et bien j'ai indiqué les accesseurs aux attributs des classes et j'ai supprimé la mention de mes fonctions "affiche" puisqu'elles n'ont plus lieu d'être. 
S'est-on mal compris sur ce qu'il fallait que je fasse ? Je n'étais pas censée parler de l'affichage de la GUI, n'est-ce pas, puisqu'il s'agit d'un manuel interne ?

**Comment by rcharb1** [comment]
A part ça, j'ai modifié l'explication des structures de données.

**Comment by pierre-H** [comment]
[Tu parles de ce fichier ?](https://github.com/pierre-H/optimiseur-coupe/blob/master/Doc/manuel d'utilisation sommaire.md)

**Comment by pierre-H** [comment]
Il n'a pas été modifié depuis 9 jours...

**Comment by rcharb1** [comment]
effectivement, ce qui s'est passé : j'étais dans le dossier src parce que j'avais eu besoin de tester le programme, et j'ai oublié où je me trouvais quand j'ai fait git add . qui n'a donc pas pris le dossier doc. C'est très bête, désolée si ça a fait perdre du temps...

**Comment by rcharb1** [comment]
corrigé

**Comment by ninja427** [comment]
Cahier des charges en cours !
