### ISSUE TITLE
Questions concernant quelques classes

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#31]
@rcharb1 : concernant la class Paire, j'ai remarqué que tout est public, même les attributs de la classe. Il y a des méthodes pour accéder aux attributs ainsi que pour modifier leurs valeurs.
Est-ce normal ?
Ne faut-il pas que au moins les méthodes getLongueur() et getPos() soient déclarées avec const ?
Merci d'avance !

**Comment by pierre-H** [comment]
J'ai remarqué aussi dans la class Combinaison que certaines méthodes n'étaient pas déclarées avec const (getRendement etc...) Est-ce normal ?

**Comment by pierre-H** [comment]
Autre question :)  : 
Dans la classe Combinaison, quelle est la différence entre les fonctions :  `list<Paire> Combinaison::getList();` et `list<Paire> Combinaison::getPaires();`

Laquelle garder ?

**Comment by rcharb1** [comment]
- Pour la question de Paire, cette classe n'est qu'un conteneur et tout ce qu'on demande à cette classe durant tout le programme, ce n'est qu'à accéder à ses attibuts. J'ai donc décidé de laisser ses attributs en publique. (j'ai déjà entendu que ça se faisait dans ce genre de cas)
- Pour ce qui est de const, j'ai tout simplement oublié, je vais corriger ça tout de suite, merci.
- getList et getPaires est aussi une erreur... c'est un doublon, j'ai gardé getPaires.

Merci beaucoup, il faut que je fasse une sérieuse relecture de ce code avant de le rendre !

**Comment by pierre-H** [comment]
Ok. Préviens-moi lorsque la relecture est terminée : ainsi je pourrai commencer la connexion entre les deux parties.

**Comment by rcharb1** [comment]
Quand je disais relecture, je voulais surtout parler de toutes les petites erreurs de style et les redondances possibles comme celle des deux fonctions d`acces. Je parlais aussi d`une meileure presentation des fonctions en blocs distincts ; fonctions d`acces, fonctions d`information, ordre d`apparition des fonctions par hierarchie des appels etc.
Je ne pense pas que ce genre de relecture soit primordial et necessaire pour joindre les deux parties du programme (d`autant que je l`ai deja relu pas mal de fois et je pense avoir elimine les erreurs les plus grossieres !) et pour moi, demain n`est pas le meilleur jour pour le faire (j`ai du temps pour travailler mais je n`ai pas vraiment acces a mon ordinateur et a mes conditions normales de travail)
Si ca ne derange pas, est-ce qu on peut assembler le programme sans cette relecture dont je m`occuperai un autre jour de la semaine ?

**Comment by pierre-H** [comment]
Ok, pas de problème. Je vais commencer alors le regroupement des deux parties.

**Comment by rcharb1** [comment]
merci !

**Comment by pierre-H** [comment]
Je reviens sur la classe Paire : peut-on du coup supprimer les méthodes permettant d'accéder aux attributs ?

**Comment by rcharb1** [comment]
oui, je vais supprimer getPos (), merci !
