### ISSUE TITLE
Xavier ?

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#32]
Salut @ninja427 ,
On a pas eu de tes nouvelles depuis quelques temps. Tout va bien ?

**Comment by ninja427** [comment]
Salut, Pierre-Emmanuel,

Maintenant tout va bien, je suis de retour. Je viens de vous envoyer un mail à tous les deux (je n'avais pas encore ouvert github). Je me remets sur le cahier des charges. Je clos cette issue !

**Comment by rcharb1** [comment]
Tout va bien ? C'était pas grave ?
