### ISSUE TITLE
3e arg de MoteurCalculs

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#35]
@rcharb1, juste pour confirmer : le 3e arg du constructeur : **double perte** c'est bien l'épaisseur de la lame, insérée par l'utilisateur, en mm ?

**Comment by pierre-H** [comment]
2e question : suis-je obligé de lancer la fonction pilote de MoteurCalculs pour lancer les calculs ou le constructeur se charge de tout ?

**Comment by rcharb1** [comment]
oui, c'est bien ça, désolée pour le temps de réponse, je crois être passée à côté

**Comment by pierre-H** [comment]
Ok, merci !
