### ISSUE TITLE
Les erreurs calculés par le moteur

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#36]
@rcharb1, je remarque que dans la fonction MoteurCalcul::affiche() tu teste et affiche en  fonction si : 
1. il y a assez ou non de matière première pour couper tous les tronçons
2. si il reste une/des barre(s) entière(s) non utilisée(s)

Ma question est : dans le cas où il n'y a pas assez de matière première (1) et/ou il reste une/des barre(s) entière(s) non utilisée(s) (2), doit-on afficher une petite fenêtre d'erreur (option A) avec un bouton ok contenant le message approprié comme pour les autres erreurs ou on affiche juste dans l'onglet résultat cette/ces informations (option B).

Personnellement, j'aurai opté pour : 
1 => option A (ou option A & B)
2 => option B

Mais j'ai l'impression que tu as fait : 
1 & 2 => option B

Qu'en pensez-vous ?

**Comment by rcharb1** [comment]
C`est effectivement l`option B que j`ai mise pour les deux.
Je pense que le plus judicieux est :
1 => option A & B
2 => option B

En effet, dans le cas 1, il est tres important que l`utilisateur sache que tous sews troncons n`ont pas pu etre coupes, d`ou le fenetre d`erreur, mais d`un autre cote, le moteur ne gere pas le manque de matiere premiere comme une erreur qui fait planter le calcul, et calcule jusqu`a ce qu`il n`y ait plus de matiere premiere. Je pense donc qu`il est sage qu`apres un message d`avertissement assez clair, l`utilisateur ait tout de meme acces aux resultats calcules : combinaison message d`avertissement (pas d`erreur) et acces aux resultats.

Ca semble plausible ?

**Comment by ninja427** [comment]
Le 2015-06-01 09:06, rcharb1 a écrit :

> Cest effectivement loption B que j`ai mise pour les deux.
>  Je pense que le plus judicieux est :
>  1 => option A & B
>  2 => option B
> 
> En effet, dans le cas 1, il est tres important que lutilisateur sache
> que tous sews troncons nont pas pu etre coupes, dou le fenetre
> derreur, mais dun autre cote, le moteur ne gere pas le manque de
> matiere premiere comme une erreur qui fait planter le calcul, et
> calcule jusqua ce quil ny ait plus de matiere premiere. Je pense donc
> quil est sage quapres un message davertissement assez clair,
> lutilisateur ait tout de meme acces aux resultats calcules :
> combinaison message davertissement (pas derreur) et acces aux
> resultats.
> 
> Ca semble plausible ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1]
> 
> https://github.com/pierre-H/optimiseur-coupe/issues/36#issuecomment-107332051

## Tout à fait !

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Ok, je vais faire cela alors.
Merci !
