### ISSUE TITLE
void List::affiche() => question

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#37]
Concernant la fonction List::affiche(), cette méthode prend en argument bool premier.
Je ne comprend pas très bien l'intérêt de cet argument car apparemment ce qu'il fait, c'est sauter l'affichage du premier élément : est-ce bien cela et est-ce normal ?

**Comment by rcharb1** [comment]
Oui, c'est tout à fait normal.
![capture du 2015-06-01 15 53 11](https://cloud.githubusercontent.com/assets/11975400/7913181/5f052a48-0876-11e5-978e-1286ee02ea35.png)

C'est le cas dans mon code, et il faut donc en tenir conpte dans l'affichage de la liste.

**Comment by pierre-H** [comment]
Merci beaucoup pour la réponse très rapide !
