### ISSUE TITLE
Résultats

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#39]
Concernant l'ajout des résultats sous forme graphique, j'ai l'impression que le texte prend déjà pas mal de place. Pensez-vous qu'il faudrait utiliser un nouvel onglet ?

De plus, ne trouvez-vous pas que le texte actuel n'est pas assez user-friendly (utilisation des crochets par exemple) ?

**Comment by rcharb1** [comment]
Oui, je pense qu'un onglet ne ferait pas de mal.
Pour ce qui est de l'affichage des résultats, supprimer les crochets serait une bonne idée, de même que modifier la police à mon avis. ça ne doit pas être compliqué, n'est-ce pas ?
Qu'en est-il de la couleur de fond de la fenêtre ? Peut-on la changer aussi ?

**Comment by pierre-H** [comment]
Quelle police et couleur de fond ? C'est quelques lignes de codes à modifier. Pas compliqué.

**Comment by rcharb1** [comment]
Je pense à une couleur de fond plus pâle, peut-être beige (#F6F292 par exemple), pour la police, peut-être Calibri ? Je ne sais pas exactement ce qu'il faudrait, mais pour l'instant ça fait  un peu texte brut,il faut qu'on trouve une police qui fasse un peu plus évolué, tout en restant simple...
