### ISSUE TITLE
Ouverture du forum de groupe

### ISSUE THREAD

**Issue by rcharb1** [pierre-H/optimiseur-coupe#4]
## Ouverture de forum de groupe

M. Bernard a dit qu'il nous ouvrirait un forum de groupe. Pour l'instant, il ne l'a pas encore fait...

**Comment by pierre-H** [comment]
A mon avis, il fera ça demain. Il va indiquer quelques procédures à suivre.

**Comment by pierre-H** [comment]
Toujours pas de groupe ...

**Comment by pierre-H** [comment]
Groupe ouvert sur l'IED !
