### ISSUE TITLE
List::append(double premier, ...)

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#40]
@rcharb1, QtCreator m'indique une petite erreur dans cette fonction bien qu'à la compilation tout se passe correctement : 

![image](https://framapic.org/BgAuJkPqZKmO/fNx3ARXr)

Même si cela ne dérange pas tant que cela, tu as une idée d'où cela provient ?

**Comment by rcharb1** [comment]
Non, je ne vois pas... quelle est l'erreur exactement ?

**Comment by pierre-H** [comment]
Les deux lignes soulignés en rouge...

**Comment by rcharb1** [comment]
Désolée, question bête de quelle est l'erreur exactement, j'avais mal lu le post et je croyais qu'il y avait un warning à la compilation dont je demandais le contenu...
Dans ce cas là, je pensequ'il doit s'agir de Qt qui ne connaît pas cette syntaxe, rien de plus à mon avis, parce que j'ai vérifié et c'est bien comme ça que ça s'utilise...
