### ISSUE TITLE
Alerte : gros bug plante ordi

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#41]
Je viens de rencontrer un bug qui fait planter mon ordi (j'ai du redémarrer en utilisant le bouton power) : 
Pour les barres : 
1. `15 cm * 1`
2. `6 cm * **2**`
Pour les tronçons : 
1. `9 cm * 1`
2. `3 cm * 2`

Ce qui est très étrange est que l'on obtiens ce bug dès que l'on modifie la quantité de la 2e saisie des barres (en gras) : à 1 aucun problème, à 2 (en haut en gras) c'est la cata au bout de quelques dizaines de secondes une fois qu'on lance le moteur : tout s'arrête, l'écran ne répond plus.
Ce bug apparaît que ce soit avec "gui+moteur" ou moteur seul via le terminal, donc je pense que c'est au niveau de l'algo.

Dans la version moteur via terminal, j'ai mis : 
`double tronconsTab [] = {15.,6.,6., 0.};`
`double barresTab [] = {9.,3.,3.,0.};`

Avec : 
`double tronconsTab [] = {15.,6., 0.};`
`double barresTab [] = {9.,3.,3.,0.};`
aucun problème

**Comment by rcharb1** [comment]
Je m'y mets...
Je serai absente demain et après-demain alors j'espère finir de résoudre ce bug avant ce soir.
Je sais que ce n'est pas le meilleur moment pour m'absenter, mais je dois encadrer une sortie de deux jours dans le nord et je n'aurai vraiment aucun accès à internet là où je serai. Je reprendrai vendredi...

**Comment by pierre-H** [comment]
Ok, pas de problème !

**Comment by rcharb1** [comment]
C'est un vrai casse-tête...
Pour l'instant, j'aimis dans le code une espèce de compteur qui fait sortir du programme dès qu'il atteint des valeurs impossibles, ce qui évite mon ordinateur de planter à chaque essai.
Maintenant, j'essaie toutes les hypothèses possibles et imaginables...Si quelqu'un a une idée d'hypothèse,je prends toujours...
Note : je travaille sur la version moteur seul pour mes essais.

**Comment by rcharb1** [comment]
Le problème vient du traitement de la perte à la coupe, il me reste à déterminer plus précisément dequoi il s'agit.

**Comment by pierre-H** [comment]
Ah bravo, c'est déjà un début !
Merci

**Comment by rcharb1** [comment]
Pour l'instant, le problème est résolu dans le moteur tout seul, mais pas encore dans l'interface. Je finirai quand je rentrerai...

**Comment by rcharb1** [comment]
Voilà, c'est fait. C'était une erreur dans la logique de la fonction attacheBarres... ça m'a pris longtemps pour trouver, mais c'est fait!
J'attaque maintenant des tests systématiques pour tester la robustesse du programme.
La recherche de ce bug m'a fait trouver un très bon moyen de limiter l'utilisateur quant aux capacités de sa machine.
Plutôt que de faire des calculs compliqués **avant le calcul** sur le rapport entre les tronçons et les barres, pour savoir si la combinatoire sera trop élevé, je vais utiliser un compteur **pendant le calcul** qui comptabilisera le nombre de boucles de moteurCalculs, et renverra un message d'erreur dans le cas où ce compteur dépassera une certaine valeur.
(pour l'instant, j'ai mis 5000, mais je vais voir jusqu'où je peux aller...)
