### ISSUE TITLE
Cours + Doxygen

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#42]
Je viens de regarder dans la section **Documents et liens** et j'ai remarqué qu'il y avait un cours et que dans le cours, il est clairement indiqué qu'[il faut utiliser Doxygen](http://foad.iedparis8.net/claroline/claroline/document/goto/index.php/LeCours/etape4.htm?cidReq=ELI421&gidReset=true).
J'invite chacun à regarder cette section et à indiquer ici les remarques nécessaires.

**Comment by pierre-H** [comment]
[Introduction :](http://foad.iedparis8.net/claroline/claroline/document/goto/index.php/LeCours/intro.htm?cidReq=ELI421&gidReset=true)

> **Validation :** la bonne réalisation de ces 4 étapes dans les délais impartis, le niveau technique du programme réalisé à l'étape 1 n'a pas d'incidence sur la note finale !
> **Documents à rendre**
> Chaque semaine :
> - le chef de projet m'envoie le compte-rendu d'avancement et des éventuels problèmes, avec copie aux membres du groupe
>   A la fin de chaque étape :
> - le groupe prépare un dossier, dont le contenu dépend de l'étape, à me remettre
> 
> A la fin de la dernière étape, en plus du dossier de l'étape, chaque membre du groupe prépare un >compte-rendu sur : 
> - bilan sur le cours
> - bilan sur le groupe (avantages et inconvénients du travail de groupe)
> - bilan sur l'expérience du rôle de chef de projet

**Comment by pierre-H** [comment]
Pour Doxygen, si quelqu'un trouve un moyen pour l'intégrer à Qt 5, qu'il l'indique ici. Je n'ai pas réussi...

**Comment by ninja427** [comment]
J'espère que ça t'aidera :
https://wiki.qt.io/Doxygen_Plugin_for_QtCreator

## 

Cordialement,

Xavier JANIN.

Elève 12316706
