### ISSUE TITLE
Réunion

### ISSUE THREAD

**Issue by rcharb1** [pierre-H/optimiseur-coupe#44]
Serait-il possible de fixer une réunion pour la dernière semaine de travail qu'il nous reste ?
De mon côté, je suis libre aujourd'hui jusqu'à 18h, et demain jusqu'à 15h.
Je pense que cette réunion se justifie, histoire de parler des derniers détails, qu'en pensez-vous ?

**Comment by pierre-H** [comment]
Moi plutôt demain.

**Comment by ninja427** [comment]
Moi aussi, plutôt demain, entre midi et deux. Ca vous va ?

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
Pour moi, ce serait bon entre midi et deux.

**Comment by rcharb1** [comment]
Je crois qu'on va abandonner pour aujourd'hui...

**Comment by ninja427** [comment]
As -tu des demandes à me transmettre que je peux avancer en attendant, autrement ?

**Comment by rcharb1** [comment]
Serait-il possible de rédiger un mail aux tuteurs pour leur demander des infos sur le déroulement de l'entretien ?

**Comment by ninja427** [comment]
Ok je fais ça dans l'après midi !
Bonne idée

**Comment by rcharb1** [comment]
Il ne faudra pas non plus oublier de rédiger chacun pour soi un petit document de conclusions sur cette expérience, donc si tu as du temps, autant en profiter

**Comment by rcharb1** [comment]
Merci !

**Comment by ninja427** [comment]
:)
La plus belle expression française : avec plaisir !

**Comment by pierre-H** [comment]
Je pense qu'il risque d'y avoir du retard car j'ai un souci concernant le rendu du graphique et je n'ai toujours pas commencer l'exportation en html...

**Comment by pierre-H** [comment]
Du coup, quand la prochaine réunion ?

**Comment by ninja427** [comment]
Pour moi pas de souci pour le retard. Je n'en aurai pas pour longtemps pour la doc utilisateur, mais il me faudra des copies d'écran

**Comment by ninja427** [comment]
Donc quand le prog sera prêt

**Comment by pierre-H** [comment]
Ok

**Comment by ninja427** [comment]
Pour moi tous les jours de semaine entre midi et deux sauf exception, le soir sinon

**Comment by rcharb1** [comment]
quand vous voulez. Pour ce qui est du retard, tu veux dire que ça ne sera pas prêt pour le 15 ?

**Comment by rcharb1** [comment]
Je peux aussi entre midi et deux tous les jours, je crois.pour le soir, en ce moment, ça dépend des heures.

**Comment by pierre-H** [comment]
@rcharb1 oui, ça risque d'être chaud, mais rien n'est certain pour le moment. Je vous tiens au courant dès que tout est ok. L'exportation HTML est un gros morceau. Le moteur graphique du programme et l'exportation de l'HTML n'ont rien à voir point de vue technique.

**Comment by pierre-H** [comment]
Je vous tiens au courant plutôt dès que j'aurai plus de certitudes...

**Comment by pierre-H** [comment]
Moi aussi entre 12 et 14h.

**Comment by ninja427** [comment]
Alors je sais qu'il est bien tard pour ce genre d'idée, mais sinon pourquoi ne pas exporter le résultat du moteur, que l'appli pourrait réouvrir et afficher ?

**Comment by ninja427** [comment]
C'est juste une idée comme ça, pour te faire gagner du temps si tu veux, sinon pas de pb, hein ?

**Comment by pierre-H** [comment]
Pourquoi pas c'est une bonne idée : ça me ferait gagner du temps à mon avis.
Si @rcharb1 est d'accord...

**Comment by rcharb1** [comment]
Que pensez-vous tout simplement d'abandonner toute idée de sauvegarde si ça représente beaucoup de travail ? le programme est si facile à utiliser...

**Comment by rcharb1** [comment]
On pourrait juste changer le cahier des charges, je ne pense pas que quelqu'un l'ait regardé en détails

**Comment by ninja427** [comment]
Dites moi je m'incline dans tous les cas, j'ai gardé tous les fichiers intermédiaires.

**Comment by rcharb1** [comment]
ce n'est pas très professionnel, mais un grand accent a été mis dans la description du projet sur le fait que ce n'est pas tant la quatlité du pgm qui compte, mais surtout de respecter les délais

**Comment by pierre-H** [comment]
Oui c'est vrai. Alors abandon du projt d'export.

**Comment by rcharb1** [comment]
ça soulagerait pas mal Pierre-Emmanuel, je crois

**Comment by rcharb1** [comment]
super !

**Comment by pierre-H** [comment]
Du coup, réunion vendredi matin ?

**Comment by ninja427** [comment]
Ok pour moi
Faut-il modifier le cahier des charges ou raconter cet abandon dans le rapport final ?

**Comment by pierre-H** [comment]
Est-ce que tout le monde a lu le cours se trouvant sur la platforme ?

**Comment by ninja427** [comment]
Vendredi midi ?

**Comment by rcharb1** [comment]
d'accord pour vendredi midi

**Comment by ninja427** [comment]
Il faut que je le relise

**Comment by pierre-H** [comment]
Pardon, vendredi midi

**Comment by rcharb1** [comment]
moi aussi

**Comment by ninja427** [comment]
Ok pour moi

**Comment by pierre-H** [comment]
Ok

**Comment by ninja427** [comment]
Est-ce que je mets à jour le cahier des charges ?

**Comment by rcharb1** [comment]
ce serait bien

**Comment by ninja427** [comment]
Ok !
Je fais ça pour vendredi !

**Comment by rcharb1** [comment]
merci !

**Comment by ninja427** [comment]
Je prépare le mail pour Josué de suite, je vous mets en copie

**Comment by rcharb1** [comment]
super, à vendredi alors

**Comment by ninja427** [comment]
A vendredi !

**Comment by pierre-H** [comment]
À vendredi

**Comment by ninja427** [comment]
Pierre ?

**Comment by pierre-H** [comment]
Oui, présent

**Comment by rcharb1** [comment]
donc on commence ici ?

**Comment by ninja427** [comment]
Salut Pierre

**Comment by pierre-H** [comment]
Salut tout le monde !
Je suis heureux d'annoncer que j'ai ENFIN trouvé le bug ce matin ! Le hic est que du coup je dois re-coder une grosse partie de la fonction graphique. Je pense que dimanche matin j'uploaderai une version finale du programme.

**Comment by rcharb1** [comment]
bravo !

**Comment by ninja427** [comment]
Bravo

**Comment by pierre-H** [comment]
Le cours dit qu'il faut en effet utiliser Doxygen. Xavier, tu y as déjà touché ?

**Comment by ninja427** [comment]
Il y a de nombreuses années, mais de mémoire ce n'est pas compliqué.

**Comment by pierre-H** [comment]
ok

**Comment by ninja427** [comment]
Ca sert à récupérer les commentaires de ton code automatiquement.
Autrement dit, code bien documenté = bonne doc

**Comment by rcharb1** [comment]
pour ce qui est de la présentation du programme, il faudrait qu'on réfléchisseà quoi devrait ressembler le paquet pour l'utilisateur

**Comment by rcharb1** [comment]
Hum, j'espère alors avoir bien fait mon travail

**Comment by pierre-H** [comment]
tu parles de l'installation ?

**Comment by rcharb1** [comment]
oui, pour l'utilisateur.

**Comment by pierre-H** [comment]
Je pense qu'il faudrait créer un fichier deb et un installateur pour Windows, cela suffit à mon avis.
(Xavier, tu vas mieux ?)

**Comment by pierre-H** [comment]
Ainsi que fichier 'code source'

**Comment by ninja427** [comment]
Oui ça va mieux.
Merci !

**Comment by ninja427** [comment]
Tu sais faire des fichiers deb ?

**Comment by pierre-H** [comment]
[Qt to Deb package](https://askubuntu.com/questions/274311/make-a-debian-package-deb-from-a-qt-project)

**Comment by pierre-H** [comment]
[tuto Qt to Deb](http://bhavyanshu.me/how-to-make-debian-packages-for-qt-c-based-applications/11/10/2014/)

**Comment by rcharb1** [comment]
super, et un installateur windows ?

**Comment by pierre-H** [comment]
[installateur windows](http://www.techrepublic.com/blog/five-apps/five-apps-for-creating-installation-packages/)

**Comment by ninja427** [comment]
Je suis bluffé...

**Comment by rcharb1** [comment]
moi aussi !

**Comment by rcharb1** [comment]
extra, je peux essayer de m'en occuper. Je ne l'ai jamais fait, donc je n'assure rien

**Comment by ninja427** [comment]
Donc, un fichier deb, un exe d'installation, une notice d'installation et un mode d'emploi ?

**Comment by rcharb1** [comment]
mais je pense que c'est quelque chose d'imporatnt à savoir faire.

**Comment by rcharb1** [comment]
et normalement, c'est censé fonctionner aussi bien sous windows que sous Linux, c'est ça ?

**Comment by pierre-H** [comment]
:)
@rcharb1  superbe. 
@ninja427 oui, avec aussi le fichier d'aide de Doxygen. Peut-être ajouter un bouton au programme qui ouvre le mode d'emploi ?

**Comment by pierre-H** [comment]
(question : le cours indique que chaque semaine, il faut envoyer un rapport à Gilles Bernard. Quelqu'un l'a fait ?)

**Comment by ninja427** [comment]
Non...

**Comment by rcharb1** [comment]
non plus... En fait, il semble qu'il y a pas mal de choses qu'on n'a pas faites

**Comment by rcharb1** [comment]
comme par exemple le chef de projet etc.

**Comment by ninja427** [comment]
On n'a pas de chef de projet

**Comment by rcharb1** [comment]
c'est ça que je dis

**Comment by ninja427** [comment]
On s'est téléscopés

**Comment by rcharb1** [comment]
lui disait que pour chaque partie il en fallait un... mais je ne croispas que ce soit si grave

**Comment by rcharb1** [comment]
je ne sais pas combien les autres groupes l'ont fait...

**Comment by ninja427** [comment]
Dans le cahier des charges j'en parle

**Comment by ninja427** [comment]
J'explique que les décisions sont prises collégialement

**Comment by pierre-H** [comment]
Du coup, je pense qu'il va falloir lui envoyer un mail : 
1. lui expliquant la situation actuelle
2. la question si une version pour linux ou windows suffit ou les 2
3. lui demander quelles sont les prochaines étapes.

**Comment by ninja427** [comment]
Tu as raison

**Comment by rcharb1** [comment]
merci @ninja427, c'est super d'en avoir parlé

**Comment by rcharb1** [comment]
c'est une bonne idée pour le mail.

**Comment by rcharb1** [comment]
qui s'en occupe ?

**Comment by pierre-H** [comment]
Xavier, peux tu faire cela ce week-end ?

**Comment by ninja427** [comment]
Je le fais
J'en profite pour lui demnder un délai ?

**Comment by pierre-H** [comment]
Superbe.
Perso, je pense que le programme sera opérationnel lundi (voir même dimanche).

**Comment by rcharb1** [comment]
Je propose qu'on attende sa réponse, parce que je ne crois pas qu'un délai soit très bien vu

**Comment by ninja427** [comment]
Ok

**Comment by rcharb1** [comment]
et selon sa réponse,il y a de grandes chances, qu'on en ait pas besoin

**Comment by pierre-H** [comment]
Autre chose à discuter ?

**Comment by rcharb1** [comment]
par contre, il faut que le mail parte très rapidement car je ne connaispas sa réactivité.

**Comment by ninja427** [comment]
On a tous un compte-rendu à faire, et je pensais à un compte rendu d'avancement global

**Comment by ninja427** [comment]
Je le ferai cet après midi et je le mettrai en priorité haute (le mail à M Bernard)

**Comment by rcharb1** [comment]
génial

**Comment by rcharb1** [comment]
sinon, il faut aussi qu'on voie pour la soutenance de projet, il y a skype sous linux, ou c'est un autre programme ?

**Comment by pierre-H** [comment]
Oui il y a Skype pour Linux, je l'utilise chaque semaine.

**Comment by ninja427** [comment]
Toi aussi tu es une associale :) ?

**Comment by rcharb1** [comment]
sort of...

**Comment by ninja427** [comment]
Ca sera l'occasion de l'installer !

**Comment by rcharb1** [comment]
c'est ça

**Comment by pierre-H** [comment]
autre chose ?

**Comment by ninja427** [comment]
Avez vous vu le planning du cahier des charges ? Pas de commentaire là dessus ? J'ai l'impression d'avoir zappé des trucs.

**Comment by rcharb1** [comment]
je n'ai pas encore vu, je regarde tout de suite

**Comment by rcharb1** [comment]
qu'entends-tu par réappropriation de ce qui a été fait avant ?

**Comment by ninja427** [comment]
Ce qui a été fait l'année précédente

**Comment by pierre-H** [comment]
Il y a selon moi une chose à modifier : 3.1 Membres du groupe : à mettre par ordre alphabétique

**Comment by ninja427** [comment]
Se le remettre dans la tête

**Comment by rcharb1** [comment]
je vois, mais je ne sais pas si M. Bernard sait qu'on avait déjà un peu commencé...

**Comment by ninja427** [comment]
Tu ne voulais pas en parler ?

**Comment by rcharb1** [comment]
je n'ai jamais pensé à le cacher, mais je n'en ai pas parlé non plus,

**Comment by pierre-H** [comment]
C'est vrai que dire directement **Réflexion et mise en route du projet** tout simplement suffit, même si je ne trouve cela pas bien méchant.

**Comment by ninja427** [comment]
Bon je modifie alors

**Comment by rcharb1** [comment]
disons que ça s'est passé d'une manière un peu spéciale : M. Bernard a validé l'idée, mais on n'avaitpas de troisièmeparticipantet je n'avais pas fini suffisamment de cours pour commencer. J'ai donc fait la majeure partie demon boulot pendant l'été dernier inofficiellement !

**Comment by ninja427** [comment]
ok, donc Pierre-Emmanuel a débuté aussi cette année ?

**Comment by rcharb1** [comment]
merci pour la modif, c'est en effet pas très conventionnel de faire le cahier des charges **après** le moteur !

**Comment by ninja427** [comment]
-> @ninja427 oui, avec aussi le fichier d'aide de Doxygen. Peut-être ajouter un bouton au programme qui ouvre le mode d'emploi ?
Je n'ai pas compris...

**Comment by pierre-H** [comment]
Moi j'ai débuté cette année la programmation de la GUI

**Comment by ninja427** [comment]
Ok. Je n'avais pas saisi tout le contexte...

**Comment by rcharb1** [comment]
désolée, si on n'a pas été très clairs...

**Comment by ninja427** [comment]
Non non pas de souci, je vais mettre à jour !

**Comment by pierre-H** [comment]
Je propose d'ajouter une bouton **Aide** dans le programme qui ouvrira le fichier **mode d'emploi**.

**Comment by rcharb1** [comment]
Pour ce qui est du mode d'emploi, que dites-vous d'un bouton AIDE dans la barre du programme

**Comment by rcharb1** [comment]
on se rejoint

**Comment by ninja427** [comment]
Ok pour moi. Quel format, le fichier ?

**Comment by ninja427** [comment]
pdf ?

**Comment by pierre-H** [comment]
En règle général, c'est plutôt en HTML ce genre de fichiers non ?

**Comment by ninja427** [comment]
Je crois que oui.

**Comment by rcharb1** [comment]
ou bien dans la fenêtre même du programme

**Comment by pierre-H** [comment]
Alors faisons en HTML. Avec LibreOffice ou Word tu exportes directement ça.

**Comment by ninja427** [comment]
Ok !

**Comment by rcharb1** [comment]
ça paraît bien !

**Comment by pierre-H** [comment]
Dans la même fenêtre, cela se fait plutôt rarement. Je pense que c'est pour éviter de charger à chaque fois le mode d'emploi

**Comment by rcharb1** [comment]
ah, ok

**Comment by rcharb1** [comment]
si on résumait :

**Comment by rcharb1** [comment]
1. Ecrire si possible,aujourd'hui à M. Bernard : Xavier
2. Faire l'installation pour linux et windows : Rebecca
3. Corriger le bug détecté : Pierre-Emmanuel

**Comment by rcharb1** [comment]
Faire la documentation avec Doxygen : Xavier

**Comment by ninja427** [comment]
Il nous reste aussi à faire :
- Documenter le programme avec doxygen
- Créer les paquets d'installation avec notice d'installation
- Ecrire un mode d'emploi
- Ecrire un rapport / historique d'avancement
- Ecrire un rapport personnel

**Comment by ninja427** [comment]
Ok pour doxygen, le mode d'emploi, et l'historique de l'avancement du projet

**Comment by pierre-H** [comment]
ok pour moi

**Comment by rcharb1** [comment]
je commence les paquets d'installation avant la réponse de M. Bernard, et s'il tarde à répondre, on sera excusés pour quelques jours de retard, car de notre côté,on aura fini à temps

**Comment by pierre-H** [comment]
Avant de créer l'installateur de windows, on attend la réponse de gilles bernard. Je pense qu'il va juste demander un fichier deb mais on ne sait jamais...

**Comment by rcharb1** [comment]
ah, d'accord, mais si j'ai le temps, c'est de toutes les façons interessant à apprendre...

**Comment by ninja427** [comment]
Au fait, l'historique de l'avancement du projet c'est pour "remplacer" les mails qu'on n'a pas envoyés

**Comment by ninja427** [comment]
Ca vous va ?

**Comment by rcharb1** [comment]
Je ne sais pas si vous partagez mon avis, mais je trouve que la fac pousse trop dans l'abstrait et la théorie et pas assez dans tout ce qui est pratique,

**Comment by pierre-H** [comment]
oui tout à fait.
@ninja427, pourras tu m'envoyer une doc qui m'explique comment je dois du coup documenter mon code en fonction des conventions de Doxygen ?

**Comment by ninja427** [comment]
En fait c'est plutôt doxygen qui s'adapte à ton code
Il repère des commentaires. Mais je t'envoie ça

**Comment by pierre-H** [comment]
@ninja427 : 

> Au fait, l'historique de l'avancement du projet c'est pour "remplacer" les mails qu'on n'a pas envoyés

Oui bonne idée !

**Comment by rcharb1** [comment]
oui, ça rattrape très bien

**Comment by pierre-H** [comment]
Pour Doxygen, ce que je veux dire c'est juste ne t'embête pas à essayer d'analyser mes commentaires. Tu n'as qu'à m'envoyer les instructions générales et moi je changerai mes commentaires.

**Comment by rcharb1** [comment]
ça m'intéresse d'avoir votre avis sur la question de la formation qu'on reçoit...
on ne nous apprend pas vraiment à créer une interface graphique, à connaître les langages utilisés aujourd'hui etc. Honnêtement, je sens qu'en sortant d'une licence,on n'est pas prête pour travailler...

**Comment by ninja427** [comment]
http://franckh.developpez.com/tutoriels/outils/doxygen/

**Comment by rcharb1** [comment]
désolée pour lehors-sujet...

**Comment by pierre-H** [comment]
Génial merci !

**Comment by pierre-H** [comment]
@rcharb1 c'est à mon avis la raison pour laquelle il y a ce genre de projets qui m'a appris énormément. Pour les facs se mettre à jour aussi rapidement que le monde de l'informatique couterait trop cher au ministère de l'éducation supérieure.

**Comment by ninja427** [comment]
Moi ce qui me hérisse c'est le premier chapitre du cours de structure de données et algo 2

**Comment by ninja427** [comment]
Tu es supposé savoir tous les types d'arbres...

**Comment by ninja427** [comment]
Ca m'énerve

**Comment by rcharb1** [comment]
et de manière générale, même pour le projet, je ne sais pas d'où vous connaissez tellement d'outil, mais en tout cas, ce n'est pas de la licence...

**Comment by ninja427** [comment]
Par contre pour avoir suivi des cours de fac en µélectronique, c'était beaucoup plus théorique que ça

**Comment by rcharb1** [comment]
et je me sens très légèrement ;-) incompétente en face...

**Comment by ninja427** [comment]
Faut pas...

**Comment by rcharb1** [comment]
bon, au moins ça rassure, il y a pire !

**Comment by ninja427** [comment]
Je pense que tu as un travail à côté ?

**Comment by rcharb1** [comment]
C'est vraiment dommage, on prend beaucoup de temps, autant apprendre plus de choses utiles de nos jours...

**Comment by pierre-H** [comment]
Pour les arbres, j'ai passé pas mal de temps sur Wikipedia.
Le pire de tous les cours pour moi c'est Algorithmique avancée de L3 : une catastrophe !
Les outils, perso, je les connais d'expérience. Je touche à l'ordi depuis que j'ai 11ans, du coup à la fin il y a des choses qui rentre. La théorie m'a fait comprendre énormément de trucs mais débuter dans l'informatique avec juste la licence de l'IED, ce n'est pas du tout à mon avis bien.

**Comment by rcharb1** [comment]
Le pire pour l'algorithmique avancée est que ça ne servira certainement strictement à rien...

**Comment by ninja427** [comment]
On est en droit de se sentir un peu laissés à l'abandon, les profs nous corrigent des mois après, etc... Mais j'ai pu lire les cours du cned il y a quelques années et c'était bien pire, je t'assure.

**Comment by ninja427** [comment]
Quelle horreur ce cours...

**Comment by ninja427** [comment]
Algo avancée

**Comment by ninja427** [comment]
Ca me rassure que vous le trouviez imbuvable

**Comment by ninja427** [comment]
Ca réduit ma sensation de nullité

**Comment by rcharb1** [comment]
de manière générale, je pense qu'ils nous donnent des bons outils pour apprendre à nous former tous seuls, mais tant qu'à faire,pourquoi ne pas nous former directement ?

**Comment by rcharb1** [comment]
presque toxique !!

**Comment by pierre-H** [comment]
Je ne sais pas vous, mais moi je galère encore avec ce cours. Le tuteur m'avais prévenu en début d'année et c'est toujours difficile pour moi !

**Comment by pierre-H** [comment]
En réalité, l'école 42 répond à ce problème. J'ai vu le programme et c'est ENORME comparé à l'IED

**Comment by pierre-H** [comment]
ENORME et GENIAL !

**Comment by ninja427** [comment]
C'est simple : regarde le genre de réponses qu'est capable de fournir un tuteur que j'évite de contacter et tu vois la politique : aide-toi et le ciel t'aidera...

**Comment by rcharb1** [comment]
au bout de 5 lectures de chaque page, on a une chance de comprendre quelque chose. J'avoue de mon côté l'avoir à peine commencé. J'attendais l'été pour avancer L3

**Comment by ninja427** [comment]
C'est celle de Xavier Niel ?

**Comment by pierre-H** [comment]
Oui.

**Comment by rcharb1** [comment]
Qui ?

**Comment by ninja427** [comment]
C'est énorme !
Samsung essaye de faire la même chose

**Comment by ninja427** [comment]
Xavier Niel le PDG de free

**Comment by pierre-H** [comment]
3 ans, niveau d'ingénieur informatique et tout ça sans cours : tu rentres là dedans et tu apprends tout seul. Tu es encadré mais tu apprends bien.
Samsung ?

**Comment by ninja427** [comment]
Oui ils essayent de monter une école du même genre

**Comment by pierre-H** [comment]
En france ?

**Comment by rcharb1** [comment]
école 42 vous dites ?  Voyons...

**Comment by ninja427** [comment]
Il me semble avoir entendu ça sur france info l'autre jour

**Comment by ninja427** [comment]
https://campus.samsung.fr/campus.php

**Comment by ninja427** [comment]
Bon en fait c'est pas aussi prestigieux

**Comment by ninja427** [comment]
Pour en finir avec l'IED c'est vrai qu'il faut être salement motivé...

**Comment by pierre-H** [comment]
Ah oui, je vois les photos. Ce n'est pas l’immense salle remplie de mac :)

**Comment by pierre-H** [comment]
Oui, bien motivé. Pour Algorithmique avancée, je suis en ce moment à la recherche d'un support pour comprendre plus facilement le cours. Si je trouve quelque chose je vous tiens au courant.
Bon courage en tous cas pour tout !

**Comment by pierre-H** [comment]
Par contre, faut faire attention car cette discussion est publique...

**Comment by rcharb1** [comment]
Bon, on continue jusqu'au bout, merci pour votre avis et bon courage !

**Comment by ninja427** [comment]
Merci avec plaisir, c'est gentil. Pour rassurer Rebecca : moi aussi il y a plein de logiciels que je découvre continuellement, innocent que je suis. L'insertion en milieu pro informatique t'apportera beaucoup là dessus.

**Comment by rcharb1** [comment]
on supprime ?

**Comment by ninja427** [comment]
J'ai un collègue auto didacte (master en philo à la base) qui me sidère tous les jours par l'étendue de ses connaissances sur le sujet...

**Comment by rcharb1** [comment]
c'est ça, pour l'instant, je cherche...Bon,il faut que j'y aille, merci beaucoup et on est contents que tu ailles mieux, Xavier

**Comment by ninja427** [comment]
Merci beaucoup à tous les deux ! Au plaisir ! Et bon courage pour ce weekend !

**Comment by rcharb1** [comment]
l'informatique est je pense **la** discipline autodidacte par excellence !

**Comment by rcharb1** [comment]
A bientôt !

**Comment by ninja427** [comment]
Il me l'a démontré !

**Comment by ninja427** [comment]
A bientôt !

**Comment by pierre-H** [comment]
A bientôt !
