### ISSUE TITLE
Nouveau bug : Fermeture du programme

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#46]
Je viens d'uploader la version avec le graphique.

J'ai remarqué que le programme, ainsi que la version avec uniquement le moteur, se ferme tout seul avec en sortie 1 lorsque je lance les calculs suivants : 
- 30 barres de 10 cm
- 60 barres de 5 cm

Un nouveau bug à corrigé ....

**Comment by pierre-H** [comment]
Idem avec dans src/main.cpp : 

```
    double barresTab [] = {100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.};
    double tronconsTab [] = {50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.,50.};
```

**Comment by rcharb1** [comment]
il ne s'agit pas vraiment d'un bug, mais du fait que je n'avais pas encore défini à partir de combien de tours de pilote on décidait d'arrêter le programme. Je viens de modifier le nombre qui était de 5000, à 3 millions, ce qui gère ce cas et jusqu'au cas de 50 barres de 10 et 100 tronçons de 5.
Dans mon ordi, la fenêtre s'est grisée pendant 2 ou 3 secondes avant de quitter. Pouvez-vous vérifier sur le vôtre, que ça n'immobilise pas l'ordi pendant trop de temps avant de quitter ? Si c'est le cas, je baisserai à 2.5 millions.
J'ai oublié d'en parler tout à l'heure, mais il n'est pas acceptable que le programme se ferme dans ce cas là... au lieu d'exit, au cas où la combinatoire est trop élevée, serait-il possible d'afficher une fenêtre d'erreur et d'arrêter le calcul ? Il s'agit de la ligne 92 de MoteurCalculs.cpp.

**Comment by pierre-H** [comment]
Oui c'est possible, mais il faut du coup que MoteurCalculs::moteurCombinaisons renvoie une valeur négative pour que la fonction qui l'a appelée elle aussi renvoie une valeur négative pour que la partie GUI puisse reconnaître qu'il y a eu une erreur. Possible ??

**Comment by rcharb1** [comment]
tout à fait, je m'en occupe tout de suite, disons que je choisis la valeur -1 pour signaler un dépassement des capacités.

**Comment by pierre-H** [comment]
Oui superbe !

**Comment by pierre-H** [comment]
Corrigé !
Du coup, il y a une incohérence : d'un point de vue technique, le formulaire accepte 9999 en quantité mais le moteur ne peut le calculer...

**Comment by rcharb1** [comment]
oui, mais comme il est difficile de savoir combien de tours de boucle engendre chaque saisie, puisque ça ne dépend pas seulement du nombre de tronçons, mais de leur taille et de celle des barres, je pense qu'il est plus pragmatique de détecter à la saisie les utilisateurs qui "exagèrent vraiment", et de repérer en cours de calcul les limitations du moteur en comptant bêtement la charge de calcul...
Je ne vois pas de méthode plus sûre pour éviter les débordements de capacité, que de les repérer pendant qu'ils ont lieu à l'aide d'un test aussi simple que if (cpt > 3 millions)... qu'en penses-tu ?
