### ISSUE TITLE
Mode d'emploi

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#47]
Je propose que dans le dossier **gui+moteur** on place un dossier  **help** avec à l'intérieur **index.html** qui sera le fichier original du mode d'emploi. Tu pourras mettre dans le dossier **help** tous les autres fichiers nécessaires (images, css...) et moi je n'aurai qu'à ouvrir le fichier **help/index.html**.

Cela te va ?

**Comment by pierre-H** [comment]
Voir plutôt index.fr.html pour le français et index.en.html pour l'anglais...

**Comment by ninja427** [comment]
Ca marche ! 
Dans un premier temps je ne pourrai faire que la version française (n'ayant pas les copies d'écran en anglais).

**Comment by pierre-H** [comment]
Pour tester le programme en anglais, dé-commente la ligne 20 du fichier main.cpp et copie le fichier **optimiseurdecoupe_en.qm** (pas .ts) dans le dossier "build" (ainsi que le dossier help si tu veux faire le test jusqu'au bout).
Utilise bien la dernière version du programme (uploadé ce soir à 22h45)

**Comment by ninja427** [comment]
Salut, il reste une phrase en français : 
![image](https://cloud.githubusercontent.com/assets/11976875/8153339/d18017de-132c-11e5-970c-3c2c12d7ee8e.png)

**Comment by ninja427** [comment]
Je pense que le message ne correspond pas : 

![image](https://cloud.githubusercontent.com/assets/11976875/8153404/e6fec118-132d-11e5-98f5-516f8d5db7ed.png)

**Comment by pierre-H** [comment]
Pour le message qui ne correspond pas, je sais : c'est une erreur dans le moteur.
Pour le message restant en français, je vais le corriger...

**Comment by ninja427** [comment]
Super ! Merci !

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Traduction corrigée !
