### ISSUE TITLE
Remarque GUI

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#48]
Merci de faire ici vos remarques sur la GUI (graphique ...)
Je vais bientôt ajouter le bouton "Aide".

**Comment by rcharb1** [comment]
D'abord, je voulais te remercier pour le changement de présentation des résultats, c'est beaucoup plus joli. Je pense qu'on peut supprimer l'affichage de l'exigence, parce que c'est plutôt quelque chose d'interne au programme.
Pour ce qui est du rendu graphique,bravo ! je pense qu'il ne serait pasinutilede faire figurer aussi la partie non-utilisée, par exemple dans une barre de 12, et on demande deux tronçons de 5, qu'on ait 5, 5 et 2. (pas oublier de prendre en compte la perte à la coupe) Qu'en penses-tu ?
Juste une idée comme ça : est-il possible de remplir en gris clair ou une couleur pastel les barres pour leur donner un aspect plus plein ?

**Comment by ninja427** [comment]
Ecoute, c'est magnifique, j'adore. Par contre j'ai relevé un petit "bug " :
![image](https://cloud.githubusercontent.com/assets/11976875/8143760/8ff6c6bc-11bc-11e5-978b-d50a34682c38.png)
L'épaisseur de lame est comprise dans les valeurs rendues par le message d'erreur.

**Comment by ninja427** [comment]
J'ai aussi ce bug : 
![image](https://cloud.githubusercontent.com/assets/11976875/8143787/1443af56-11be-11e5-9a6c-ca10590b2641.png)
La quantité en entrée est pourtant suffisante.

**Comment by ninja427** [comment]
Et si je demande une nouvelle saisie la fenêtre se ferme.

**Comment by ninja427** [comment]
Pour finir, pour cette demande : 
![image](https://cloud.githubusercontent.com/assets/11976875/8143798/a3662c68-11be-11e5-96b5-1d47e523ec25.png)
J'ai ce résultat graphique : 
![image](https://cloud.githubusercontent.com/assets/11976875/8143799/b12acf7a-11be-11e5-880c-b2d94243e1b5.png)

**Comment by pierre-H** [comment]
Pour l'histoire du graphique où l'on ne voie plus les mesures : corrigé.
La fenêtre qui se ferme toute seule en cliquant sur appliquer : le debugger ne trouve rien. Je vais devoir creuser un peu plus seul.
Les autres erreurs proviennent du moteur. @rcharb1 a été mise au courant.
Merci pour ton retour !
(Attention a bien utiliser la dernière version du programme lors de vos tests.)

**Comment by ninja427** [comment]
Avec plaisir !

J'ai fait le mode d'emploi en français, j'ai corrigé le cahier des 
charges, et je continue sur le reste.

Bon courage

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Je viens d'ajouter une fonction intéressante à la gui : l'affichage des restes dans le graphique : 
![restes](https://framapic.org/8xJOmYlXlhP5/VEu64gAp)

**Comment by rcharb1** [comment]
C'est vraiment vraiment super ! Très beau, très propre !

**Comment by rcharb1** [comment]
Un petit commentaire : quand on demande des tronçons en une certaine unité, les résultats sont toujours en cm, du coup l'utilisateur aura peut-être du mal à reconnaître  que c'est ce qu'il a demandé. Serait-il possible de retenir l'unité qu'il a demandée, et rendre les résultats dans la même unité ?
(Un truc du style : associer chaque tronçon lors de la saisie à son unité, et retenir cette association dans une table qu'on consulte à nouveau quand on renvoie les résultats...)
Ce serait encore "un plus en plus" :-)
Merci pour tout ce beau travail !

**Comment by pierre-H** [comment]
Alors normalement il y a déjà la méthode statique ConvertUnit::toStrSimplifie(double) qui permet à partir d'un double de mm de renvoyer la meilleur écriture possible.
Fais un test avec des milliers de cm et le résultat sera en m.

-----Message d'origine-----
De : "rcharb1" notifications@github.com
Envoyé : ‎16/‎06/‎2015 08:13
À : "pierre-H/optimiseur-coupe" optimiseur-coupe@noreply.github.com
Cc : "Pierre" eytanpierre@gmail.com
Objet : Re: [optimiseur-coupe] Remarque GUI (#48)

Un petit commentaire : quand on demande des tronçons en une certaine unité, les résultats sont toujours en cm, du coup l'utilisateur aura peut-être du mal à reconnaître que c'est ce qu'il a demandé. Serait-il possible de retenir l'unité qu'il a demandée, et rendre les résultats dans la même unité ?
(Un truc du style : associer chaque tronçon lors de la saisie à son unité, et retenir cette association dans une table qu'on consulte à nouveau quand on renvoie les résultats...)
Ce serait encore "un plus en plus" :-)
Merci pour tout ce beau travail !

**Comment by pierre-H** [comment]
Pardon. Essaye plutôt avec 100 cm et le résultat affichera 1m.

**Comment by rcharb1** [comment]
et pour ce qui est des feet et inches, n'est-il pas mieux de les laisser comme les désirs de l'utilisateur ?

**Comment by pierre-H** [comment]
Cela fonctionne de la même façon.
J'ai inséré dans le programme une fonction de Qt qui repère les réglages d'y système. Si celui-ci utilise le système métrique alors on renvoie une unité métrique. Sinon on passe en feet et inches.

-----Message d'origine-----
De : "rcharb1" notifications@github.com
Envoyé : ‎16/‎06/‎2015 12:34
À : "pierre-H/optimiseur-coupe" optimiseur-coupe@noreply.github.com
Cc : "Pierre" eytanpierre@gmail.com
Objet : Re: [optimiseur-coupe] Remarque GUI (#48)

et pour ce qui est des feet et inches, n'est-il pas mieux de les laisser comme les désirs de l'utilisateur ?

**Comment by rcharb1** [comment]
Je comprends, merci, donc on ne tient pas compte de la saisie, mais des préférences générales de l'utilisateur, il serait peut-être utile de le dire dans les spécifications, non ? Qu'en pense @ninja427 ?

**Comment by pierre-H** [comment]
Ah oui c'est vrai que c'est à préciser !

**Comment by ninja427** [comment]
Je l'implémenterai dès que possible

**Comment by rcharb1** [comment]
merci !
