### ISSUE TITLE
Erreurs à la compilation

### ISSUE THREAD

**Issue by rcharb1** [pierre-H/optimiseur-coupe#49]
Depuis ce soir, j'ai une erreur à la compilation : 

![erreurs](https://cloud.githubusercontent.com/assets/11975400/8145891/b3f2815c-1223-11e5-8239-92f8f5798e0a.png)

Une idée ?

**Comment by pierre-H** [comment]
Oui, je vais le résoudre...

-----Message d'origine-----
De : "rcharb1" notifications@github.com
Envoyé : ‎13/‎06/‎2015 22:27
À : "pierre-H/optimiseur-coupe" optimiseur-coupe@noreply.github.com
Objet : [optimiseur-coupe] Erreurs à la compilation (#49)

Depuis ce soir, j'ai une erreur à la compilation : 

Une idée ?
