### ISSUE TITLE
Répartition des tâches

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#5]
Rébecca, une idée concernant la répartition des tâches ?

**Comment by rcharb1** [comment]
@ninja427 et @pierre-H Je pense qu'il faut tout d'abord qu'on discute sur le forums de notre groupe de tout ce qu'il faut modifier, corriger, et ajouter comme fonctionalité, et ensuite, décider de tout ça, qu'est-ce qui va être fait par chacun. Autrement dit,
1. Décider de ce qu'il **y a à faire**
2. Décider de **ce que chacun va faire**
Sachant que dès qu'on aura dressé la liste de toutes les tâches et qu'on aura dessiné plus clairement le cahier des charges, tout semblera beaucoup plus clair. Mais il faudra pour cela se fixer une session de discussion, un RDV sur le [chat de notre groupe :](http://foad.iedparis8.net/claroline/claroline/chat/chat.php?cidReq=ELI421&gidReq=7) de mon côté, je peux demain toute la journée, jusqu'aux environs de 4 heures.
Quelles sont vos disponibilités ?

**Comment by pierre-H** [comment]
Moi je peux demain de 9h à 16h.

**Comment by ninja427** [comment]
Le 2015-04-20 22:08, Pierre a écrit :

> Moi je peux demain de 9h à 16h.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] 
> https://github.com/pierre-H/optimiseur-coupe/issues/5#issuecomment-94555613

Pour moi ce sera plus compliqué...
En fait il y a actuellement une situation de crise à mon job.
Par contre je m'en voudrais de vous pénaliser (alors que vous n'y êtes 
absolument pour rien), mais je me vois malheureusement contraint 
d'imposer une plage de 12h30 à 14h00 (max), ce qui est fort peu 
courtois, d'autant pluss que je n'aurai pas encore fait la revue de code 
(mais je ferai le maximum pour trouver le temps de la faire demain 
matin).

J'espère que ceci vous conviendra.

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
Pour moi, c'est bon de 12h30 à 14h ! je ne pense pas qu'il faille tellement plus, mais ce sera plus efficace si on réfléchit chacun de son côté sur les fonctionnalités qui peuvent être attendues avant, même si on n'a pas vraiment vu le code.
Bonne nuit !

**Comment by pierre-H** [comment]
Moi aussi, c'est ok 12h30 - 14h.

Bonne nuit !
