### ISSUE TITLE
Moteur : petits bugs

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#50]
@rcharb1 j'ai l'impression que pilote() renvoie -1 aussi lorsqu'il n'y a pas assez de matière première pour couper tous les tronçons désirés (erreur calculé par le moteur).
Testé avec : 
- Barres av. dec. : 10 cm \* 50
- Troçons des. : 49 cm *1
  Les deux messages d'erreurs s'affichent : calculs trop grands et pas assez de matière première. Avec le moteur j'obtiens un résultat bizarre...

Concernant la remarque de @ninja427 [ici](https://github.com/pierre-H/optimiseur-coupe/issues/48#issuecomment-111690078) je pense que c'est un problème au niveau du moteur que la List moteur->getTroncons() contiens les longueurs + l'épaisseur de lame. Non ?

**Comment by rcharb1** [comment]
Je voudrais bien m'en occuper, mais j'ai plein d'erreurs à la compilation, pas vous ?
![erreurs](https://cloud.githubusercontent.com/assets/11975400/8154643/c996c69a-1344-11e5-9c56-9486fcddc0ce.png)

**Comment by pierre-H** [comment]
Non, rien chez nous.
Es-tu certaine d'avoir la dernière version de Qt (utilise Qt Maintenance pour mettre à jour) ?
Je te conseil aussi de supprimer ton projet (il faut supprimer le dossier source et build dans le workspace de Qt) et de le créer à nouveau en copiant les fichiers à partir de ton git local (mis à jour via git pull).

**Comment by pierre-H** [comment]
Réglé ?

**Comment by rcharb1** [comment]
J'ai honte... je n'avais pas updaté qt lorsque tu nous avais dit de le faire... Où se trouve ce Qt maintenance ? Je ne le trouve pas...

**Comment by pierre-H** [comment]
Si tu as Ubuntu, utilise la recherche en tapant juste Qt. Sinon, dans le dossier d'installation de Qt, il y a le fichier **MaintenanceTool** à ouvrir.

**Comment by rcharb1** [comment]
J'ai Ubuntu, et c'est bien la première chose que j'ai essayée (d'utiliser la recherche), ça n'apparaît pas.
Je vais chercher le dossier d'installation de Qt...

**Comment by rcharb1** [comment]
Pour ce qui est du packaging, je suis en train de suivre le tutoriel indiqué, et franchement, je dois dire que c'est trop dur pour moi... Je suis les instructions, mais comme je ne comprends pas vraiment ce que  je fais,  ça ne marche évidemment pas... Je continue à m'accrocher, mais je ne  sais  pas si j'y arriverai... Une de vous deux l'aurait-il déjà fait et pourrait me donner un coup de main ?

**Comment by pierre-H** [comment]
Je ne l'ai jamais fait, mais je vais regarder de plus prêt...

-----Message d'origine-----
De : "rcharb1" notifications@github.com
Envoyé : ‎15/‎06/‎2015 14:41
À : "pierre-H/optimiseur-coupe" optimiseur-coupe@noreply.github.com
Cc : "Pierre" eytanpierre@gmail.com
Objet : Re: [optimiseur-coupe] Moteur : petits bugs (#50)

Pour ce qui est du packaging, je suis en train de suivre le tutoriel indiqué, et franchement, je dois dire que c'est trop dur pour moi... Je suis les instructions, mais comme je ne comprends pas vraiment ce que je fais, ça ne marche évidemment pas... Je continue à m'accrocher, mais je ne sais pas si j'y arriverai... Une de vous deux l'aurait-il déjà fait et pourrait me donner un coup de main ?

**Comment by rcharb1** [comment]
Vraiment désolée de te rajouter une charge alors que je pensais être capable de le faire...

**Comment by rcharb1** [comment]
ça y est, au moins, là, ça marche pour moi, il n'y a plus d'erreur...

**Comment by rcharb1** [comment]
Xavier, peux tu regarder aussi, et si tu sens que c'est dans tes cordes, le faire ? Point de vue Gilles Bernard, cela ajoutera un côté programmation à la liste de ta contribution au projet.
Merci d'avance !

**Comment by ninja427** [comment]
Tu parles de créer un deb, c'est ça ?

**Comment by rcharb1** [comment]
oui, c'est ça. Qu'en penses-tu?

**Comment by ninja427** [comment]
Je peux attaquer demain matin. Ca vous va ?

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
c'est parfait. On aura donc un petit retard, mais après tout, on attend toujours son mail de retour...

**Comment by rcharb1** [comment]
merci !

**Comment by ninja427** [comment]
:)

**Comment by pierre-H** [comment]
Pour revenir au sujet original, @rcharb1, si tu veux voir le premier bug, il faut commenter la ligne 91 : `return;` du fichier fenetreprincipale.cpp

**Comment by pierre-H** [comment]
Concernant toujours ce premier bug, à la ligne 71 du fichier MoteurCalculs.cpp il y a : 
`if (moteurCombinaisons(*liste) == -1) return (-1);`
Donc un autre retour de -1. Le problème est que si je met cette ligne à -2 ou la ligne 78 à -2, on a toujours le même bug. Une idée ?

**Comment by rcharb1** [comment]
pour ce qui est du moteur qui renvoie -1 dans le mauvais cas, c'est corrigé.
Pour les autres bugs, je me mords les doigts d'avoir mal évalué le choix de ma structure de données pour ce qui est des listes de tronçons.
Je veux dire par là que le programme gère des tronçons de la même taille comme s'il s'agissait de tronçons de taille différente et les combine donc tous au même titre... Il faudrait au contraire regrouper les tronçons de même taille au sein d'une liste à part dans la liste des tronçons, et ne combiner qu'un exemplaire de chaque longueur. Il est en effet ridicule que le programme atteigne le maximum de ses possibilités de calculs pour une requête aussi simple que 49 tronçons de 1 cm sur une barre de 50, et c'est effectivement le cas car il combine bêtement tous les tronçons de 1...
Je vais essayer de voir ce que je peux faire demain, même si on est déjà en retard... Est-ce que j'arriverai à effectuer ces modifications en une journée sans créer de nouveaux bugs...
désolée...

**Comment by pierre-H** [comment]
C'est déjà ça. Avoir remarqué le bug et la réflexion sur le choix de la structure sont de bonnes avancées qui nous mettent dans une situation de programmation véritable.
On avance, on remarque des choses, c'est en soi génial !

**Comment by pierre-H** [comment]
Nouveau bug : 
* Barres av. déc. : 1m *1
* Tronçons désiré : moins de 5cm *2

Indique que l'on a pas assez de matière première. A partir de 5cm et plus aucun problème...

**Comment by rcharb1** [comment]
Est-ce qu'il y a eu un message ici qui a été effacé ?

**Comment by pierre-H** [comment]
Oui. Je l'ai mis dans une issue à part

-----Message d'origine-----
De : "rcharb1" notifications@github.com
Envoyé : ‎16/‎06/‎2015 12:35
À : "pierre-H/optimiseur-coupe" optimiseur-coupe@noreply.github.com
Cc : "Pierre" eytanpierre@gmail.com
Objet : Re: [optimiseur-coupe] Moteur : petits bugs (#50)

Est-ce qu'il y a eu un message ici qui a été effacé ?

**Comment by rcharb1** [comment]
C'est vrai qu'il est très interessant d'analyser les problèmes et de trouver des solutions. Il est encore plus intéressant d'en tirer leçon pour être à même plus tard de trouver les solutions de structures de données adaptées avant même de commencer à coder, après tout, c'est ça (entre autres) l'expérience !
Pour ce qui est de la modification des structures de données, j'avais pensé à passer d'une liste de tronçons de ce style : (dans les carrés, la longueur du tronçon, au dessus,son index dans la liste des tronçons) 
![avant](https://cloud.githubusercontent.com/assets/11975400/8184581/da4603d0-1447-11e5-9a0f-d9a9fea33c34.jpeg)

à une liste des tronçonsde ce type  où l'on aurait regroupé les tronçons de même longueur dans une liste à part dont on n'utiliserait qu'un seul exemplaire lors des combinaisons : 
![apres](https://cloud.githubusercontent.com/assets/11975400/8184763/f76c7e20-1448-11e5-8c99-20e87bd8687f.jpeg)

J'ai renoncé à cette modification pour plusieurs raisons : 
1. Parcequ'on ne **peut pas** prendre uniquement un exemplaire de chaque groupe, il faut en effet dans ce cas-là générer les combinaisons 3, 3 3 , 3 3 3, et 3 3 3 3, mlais sans générer 4 fois ces combinaisons en commençant à chaque fois par un 3 différent... Donc algorithmiquement, ça aurait été difficile, en tout cas pour moi, de trouver la manière de le faire, alors que la fonction qui s'occupe des combinaisons est à l'origine une fonction récursive toute simple...
2. Parceque cela ferait changer tout le moteur de façon drastique, il faudrait adapter àpeu près toutes les fonctions, ce qui représente un travail effrayant et assez peu adapté à la date d telle que d='date de fin du projet + 1'
3. Parce que j'ai trouvé une bien meilleure solution (lire : bien plus simple !) Je ne l'ai pas encore implémentée, mais je poste parceque c'est j'ai trouvé très intéressant ce va et viens entre modification de str de données donc d'algorithme également, et changement d'algorithme uniquement. Ce post me met aussi les idées au clair.
La solution serait : avant de commencer une nouvelle branche de la combinaison, de vérifier s'il y a une branche déjà existante dans la liste des possibilités qui commence par un tronçon de même longueur, mais d'index différent dans la liste des tronçons, auquel cas, on taille tout simplement cette branche !

Ex : 
tronçons :  2 2 3 
Avant, ils étaient combinés ainsi : 
2             // première branche
    2  2
        2 2 3
    2 3
2           // deuxième branche qui va être taillée
    2 3
3           // troisième branche
Maintenant, ils seront combinés ainsi : 
2           // première branche
    2  2
        2 2 3
    2 3
3           // deuxième branche
Ici, ça ne fait pas beaucoup de différence, mais dans une vraie combinatoire, ça change tout ! Bon, à la pratique !
(j'ai partagé parce que j'ai trouvé ça tellement intéressant : on peut être assis devant mon ordi pendant trois jours à essayer d'appliquer une solution compliquée, alors qu'on pourrait le faire en 1 heure au plus avec une autre solution !)

**Comment by pierre-H** [comment]
Génial ! Très intéressant.

**Comment by rcharb1** [comment]
Encore un autre bug dont je vais essayer de m'occuper demain : 
quand les seules combinaisons qui permettent d'utiliser tous les tronçons donnent des exigences qui ne sont pas des multiples de 10, ça indique qu'il n'y a pas assez de matière première, alors qu'il y en a largement assez... Je le sais parce que l'exigence baisse de 10 en 10 si la liste des possibilités est vide, et que ce problème apparait le même si on baisse de 5 en 5, mais pour les non-multiples de 5 seulement...
ça ne devrait pas se comporter comme ça, je ne sais pas encore pourquoi, j'essaierai de régler ça demain en même temps que je ferai une dernière relecture du programme.

**Comment by rcharb1** [comment]
Suite des péripéties : ma solution n'était bonne que pour les combinaisons qui ont dépassé le niveau d'exigence et donc ont été mémorisées dans la liste des possibilités. Pour celles qui n'ont pas été mémorisées, on a le même problème car quand le programme recherche s'il y a déjà des combinaisons qui commencent par cette même longueur de tronçon, il n'y en a pas, et il mouline donc indéfiniment. C'est par exemple le cas avec 1 barre de 100 et des 100 tronçons de 0.01...
Il faut donc penser à une solution très légèrement différente !
