### ISSUE TITLE
Pas assez de matière première

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#52]
Nouveau bug : 
- Barres av. déc. : 1m *1
- Tronçons désiré : moins de 5cm *2

Indique que l'on a pas assez de matière première. A partir de 5cm et plus aucun problème...

**Comment by rcharb1** [comment]
ça pousse bien ici ces petites bêbêtes !
Plus sérieusement, je sais d'où ça vient, de cette histoire d'exigence qui baisse de 10 en 10, et ça passe de l'exigence de 10 à 0 directement... Donc pour une combinaison qui est en dessous de l'exigence 10, elle n'est  pas retenue...
Je m'en occupe maintenant, merci de me l'avoir signalé...

**Comment by rcharb1** [comment]
Voilà, c'est fait, maintenant, je m'occupe de la modification des structures de données... En espérant ne pas rencontrer trop de difficultés...

**Comment by pierre-H** [comment]
Génial ! Merci !
