### ISSUE TITLE
Onglet "A propos"

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#53]
Ne devrait-on pas mettre un onglet "A propos" avec : 
- nos noms
- une mention "_fait dans le cadre de l'IED Paris 8_"
- l'adresse du projet Github
- La licence du logiciel ([à choisir](http://choosealicense.com/))

Qu'en pensez-vous ?

**Comment by rcharb1** [comment]
Je suis COMPLETEMENT passé à côté de ce post... Toutes mes excuses... Il est un peu tard maintenant...

**Comment by pierre-H** [comment]
Si vous pensez que cela pourrait être bien, je peux toujours le rajouter.
Comme vous voulez...

-----Message d'origine-----
De : "rcharb1" notifications@github.com
Envoyé : ‎28/‎06/‎2015 09:47
À : "pierre-H/optimiseur-coupe" optimiseur-coupe@noreply.github.com
Cc : "Pierre" eytanpierre@gmail.com
Objet : Re: [optimiseur-coupe] Onglet "A propos" (#53)

Je suis COMPLETEMENT passé à côté de ce post... Toutes mes excuses... Il est un peu tard maintenant...

**Comment by rcharb1** [comment]
Et c'est possible de l'intégrer facilement au packaging déjà fait ? (Comment fait-on ?)

**Comment by ninja427** [comment]
Il faudrait refaire la compilation et le packaging

**Comment by rcharb1** [comment]
compliqué ?

**Comment by ninja427** [comment]
Long...

**Comment by rcharb1** [comment]
Alors on abandonne pour ça je pense... C'est du plus... Mais qu'en est-il du post que je viens d'écrire ? ça me paraît important... C'est vraiment bête de ma part de na pas y avoir pensé avant. 
Est-ce que ce n'est pas possible de compiler en dehors du packaging avec les sources du dossier gui+moteur, de récupérer l'exécutable, et de le rajouter à l'archive dans bin ?

**Comment by ninja427** [comment]
Je viens de voir ton autre post. Je suggère donc que vous fassiez toutes les modifications dans le dossier gui+moteur, je ne pourrai pas refaire le packaging avant ce soir ou demain matin.

**Comment by rcharb1** [comment]
I feel bad... C'est certain qu'il faut refaire **tout** le packaging ? Désolée d'insister, je ne m'y connais pas et je ne sais pas comment tu as fait, mais n'est-il vraiment pas possible de changer uniquement l'exécutable en l'ayant créé  à partir d'une compilation dans gui+moteur ?

**Comment by ninja427** [comment]
Si mais il faut refaire l'archive deb, tu ne peux pas modifier une partie. Mais ne t'inquiète pas je le ferai. Tenez moi au courant. Vous ajoutez l'onglet ou pas ?

**Comment by rcharb1** [comment]
Je suis d'avis que c'est une bonne idée, mais si ça implique un délai supplémentaire, non... De mon côté, j'ai déjà rajouté cette petite instruction dans mon dernier commit, donc c'est prêt à être re-packagé... Donc si cet onglet peut être fait avant ce soir, super, sinon, et bien je crois qu'il vaut mieux ne pas se risquer à plus de retard. Encore une fois confuse de cette négligence et que ça te donne plus de boulot...

**Comment by ninja427** [comment]
Bon en fait quand je disais long c'est parce que j'ai cru devoir tout refaire. Mon chat a marché (ou dormi) sur mon clavier une nuit, je n'arrivais pas à redémarrer mon pc, et les fichiers intermédiaires n'étaient pas sur le cloud => j'ai tout perdu. En fait avec un gestionnaire d'archive tu peux décompresser un paquet deb et tout récupérer. Donc tout va bien. Mais je dois faire mon rapport (sous windows) et finir la reinstall pourrefaire le packaging. Donc pour ce soir.

**Comment by rcharb1** [comment]
génial, merci beaucoup !  Que pense @pierre-H pour l'onglet "à propos" ?

**Comment by pierre-H** [comment]
Personnellement, je pense pouvoir ajouter l'onglet aujourd'hui sans problèmes.
Vous souhaitez que je mette quelque chose de particulier à part nos noms, adresses mail et mention de l'IED ?

**Comment by rcharb1** [comment]
Je ne pense à rien de particulier... On prend MIT comme licence ? Ou rien ? A quoi sert exactement la licence ?

**Comment by ninja427** [comment]
J'ai mis gpl3 dans le .deb

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
C'est fait !

**Comment by ninja427** [comment]
Vendu !
Je refais le packaging ce soir.

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by ninja427** [comment]
Packaging fait !
