### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by rcharb1** [pierre-H/optimiseur-coupe#54]
@ninja427 Comment se passe le packaging ? Tu te débrouilles ?
(Je pense qu'on ne devrait pas trop tarder à rendre...)

**Comment by ninja427** [comment]
Je pense que j'ai fait un tiers du boulot...

A mon avis, connaissant le rythme de Gilles Bernard, on est tranquilles 
jusqu'à lundi...

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
super ! Bravo !

**Comment by ninja427** [comment]
J'ai posté ce que j'ai fait, je n'en suis pas très content, mais bon j'ai passé la journée dessus... En fait avec qt4.8 ça n'aurait guère posé de pb, car j'aurais pu ajouter les lib statiques et ne pas avoir à gérer les dépendances. Il reste deux soucis : la non prise en compte de l'icone, et le fait que le bouton aide pointe vers un chemin absolu... De toute façon tout semble remis en cause par le mail que vient d'envoyer Gilles Bernard...

**Comment by ninja427** [comment]
Vu dans le forum du groupe : il accepte un script utilisant cmake. J'essaye de m'y remettre demain.

**Comment by rcharb1** [comment]
où en est-on ? Besoin d'aide ?

**Comment by ninja427** [comment]
C'est en cours

## Je travaille dessus le matin, le midi et le soir.

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
Bon courage... Heureusement que tu gardes la nuit pour toi...

**Comment by rcharb1** [comment]
Peut-être que @pierre-H qui s'est occupé de gérer tous les fichiers du projet et la compilation avec Qt, pourrait te donner qualques informations utiles ?

**Comment by ninja427** [comment]
J'ai laissé tomber l'idée du script à cause de la gestion des dépendances... Même dans un fichier deb ça n'a pas été simple... Pour l'instant il n'y a que la version amd64, mais je peux créer assez facilement la version i386 si besoin. Pour tester dpkg -i cutting_optimizer-1.0.0-amd64.deb ou gdebi -n cutting_optimizer-1.0.0-amd64.deb. Le script à côté sert à ajouter le ppa qt à la liste des dépôts, pour installer automatiquement les dépendances. Si je l'insère dans le deb en preinstall ça génère des erreurs.

**Comment by ninja427** [comment]
La commande : cutting_optimizer, installée dans /usr/bin

**Comment by ninja427** [comment]
J'ai modifié le code pour l'adressage des fichiers d'aide (3 fichiers + 6 entrées dans le fichier de traduction), ça ne marchait pas sinon.

**Comment by ninja427** [comment]
Il installe les sources aussi dans /usr/share/cutting_optimizer/src/, les fichiers d'aide dans /usr/share/cutting_optimizer/help/, le fichier /usr/share/applications/cutting_optimizer.desktop et le fichier icone /usr/share/pixmaps/cutting_optimizer.pxb.

**Comment by ninja427** [comment]
Testé sur le pc d'un collègue xubuntu 14.04 xfce : ça marche

**Comment by rcharb1** [comment]
Testé sur le mien, ça marche aussi, bravo !!!
Bon, alors on rend aujourd'hui ? Comment, et quoi ?

**Comment by ninja427** [comment]
J'ai encore un update du cahier des charges à faire (demain) + 1 rapport  à faire (dimanche au plus tard). As-tu fait le tien au fait ?
Donc lundi je pense

**Comment by rcharb1** [comment]
Je suis en train de rédiger le mien, donc à mon avis, lundi serait parfait ! 
Encore une fois bravo, c'est une chose de rentrer sur Qt et de compiler son programme, mais c'est une autre de chercher le nom de son programme dans le finder et de voir la jolie visseuse jaune s'afficher!

**Comment by ninja427** [comment]
Merci beaucoup c'est très gentil. La pression retombe... J'ai fini ça à 1 h 30 du mat... Mine de rien la visseuse qui s'affiche j'ai eu du mal à cause de la confusion qui règne autour des paquets deb. A noter que cutting_optimizer est visible dans les applications installées

**Comment by pierre-H** [comment]
ça marche aussi chez moi !!!
Bravo Xavier !!!!

**Comment by ninja427** [comment]
:)))) \o/

**Comment by ninja427** [comment]
Merci de re-tester le packaging s'il vous plait. Chez moi c'est bon.
Bonne soirée !

**Comment by pierre-H** [comment]
Non, le deb qui est sur Github n'est n'installe pas la version avec l'onglet info chez moi...

**Comment by ninja427** [comment]
Bon, je comprends pas trop ce qu'il s'est passé... Du coup j'ai recréé un nouveau paquet que je viens de charger, à tester donc...

**Comment by pierre-H** [comment]
Peut-être faudrait-il changer le num du deb (1.0.0 là ...)

**Comment by pierre-H** [comment]
C'est bon ! Le deb fonctionne sans problème avec l'onglet info.

**Comment by ninja427** [comment]
\o/

J'vais m'coucher...

Bonne nuit !

**Comment by rcharb1** [comment]
Génial !

**Comment by ninja427** [comment]
Youhou !
