### ISSUE TITLE
Avancement des travaux, date limite

### ISSUE THREAD

**Issue by rcharb1** [pierre-H/optimiseur-coupe#55]
Bonsoir,
Je voulais avoir votre avis sur la situation présente.
D'un côté, il semble évident que notre programme serait loin de souffrir de quelques jours de plus de mise au point, vu le nombre de bugs qu'on a déjà trouvés et les améliorations qu'on a réussi a y apporter jusqu'à présent... Il aurait été dommage de le présenter sans ces corrections ! Et il semble probable que nous dirions la même chose dans 3 jours...
D'un autre côté, il y a une date limite qu'il faut honorer et j'ai cru comprendre dans le document du cours que c'était un critère déterminant dans l'évaluation, en tout cas, plus que le niveau de complexité du programme, qui, selon M. Bernard, pourrait même être fait sans interface graphique !!!
Dans ce sens, on peut dire qu'en réalité, on ne fait qu'attendre la réponse de M. Bernard concernant le packaging, et qu'entre temps, et bien pourquoi pas ne pas améliorer un peu notre programme, ce qui s'entend, mais je pense que continuer ce petit jeu au delà de la fin de semaine ne serait pas bon du tout...
Qu'en dites-vous ?
Je vais poster un message sur notre forum de groupe au cas où M. Bernard s'y promènerait...

**Comment by pierre-H** [comment]
Personnellement, je pense que tant que nous n'avons pas eu de signe de la part de Gilles Bernard, on pourrait en profiter pour régler les quelques bugs qui se présentent.
On est pas obligé de s'y mettre à fond jusqu'à la réponse de Gilles Bernard, mais je pense que ce serait dommage de ne pas profiter de ces quelques jours pour rendre un peu plus stable le programme.
En deux mots : je suis pour une approche modéré -> profiter du temps sans pour autant se mettre une pression de

**Comment by rcharb1** [comment]
D'accord, je propose qu'on se fixe cette approche jusqu'à vendredi  et qu'on en rediscute si rien ne se passe entre temps.

**Comment by pierre-H** [comment]
Bon, toujours rien.
Que faisons-nous ?
(Je dois préciser que j'ai un stage en juillet. A part entre 12 et 14h, je n'aurai pas beaucoup de temps en semaine.)

**Comment by rcharb1** [comment]
Je suis d'avis de rendre le plus rapidement possible, c'est à dire dès que le packaging sera fini. Il est clair que tout n'est pas complètement parfait, j'ai encore beaucoup travaillé dessus ces derniers jours, sans parvenir à des améliorations fulgurantes, et je pense qu'il y a un moment où il faut se dire "ça suffit"...
Voilà mon avis... @ninja427 qu'en penses-tu ?

**Comment by ninja427** [comment]
Je bute sur le packaging en deb... Mais j'ai enfin quelques heures 
devant moi. Je me demande s'il ne serait pas mieux de créer un script 
d'installation. Je vous tiens au courant.

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
De ce qu'on nous a répondu sur notre forum, il semble qu'un script d'installation fasse l'affaire aussi... donc ce n'est pas du tout grave si on se rabat dessus...

**Comment by pierre-H** [comment]
@ninja427 comment va le packaging ?

**Comment by ninja427** [comment]
C'est la merde. Je m'y remets demain après midi.
