### ISSUE TITLE
UML

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#57]
J'ai suivi les indications de Gilles Bernard concernant l'UML.
J'ai uploadé le fichier. N'hésitez-pas à regarder si vous voyez quelque chose à modifier...

**Comment by rcharb1** [comment]
Désolée pour le délai de réponse... Merci beaucoup de t'en être occupé. Je vais mieux regarder et te dire si j'ai des choses à modifier

**Comment by rcharb1** [comment]
Quand j'ouvre l'UML sous Umbrello, voilà ce que j'obtiens... Je suppose que ce n'est pas ce que c'est censé donner... Avec quoi suis-je censée l'ouvrir ?
![umbrello](https://cloud.githubusercontent.com/assets/11975400/8312146/bd5c12e0-19e3-11e5-9f5e-f8a08a2a97b6.png)

**Comment by pierre-H** [comment]
J'utilise umbrello 2.15.3. J'ai ajouté l'image...

**Comment by rcharb1** [comment]
Ah, c'est autre chose, merci ! J'étais sous 2.13.3, pas trop étonnant que ça ne marche pas...

**Comment by pierre-H** [comment]
Perso, avec Xubuntu, je n'ai fait qu'un `sudo apt-get install umbrello` et je n'arrive pas à savoir quelle est la dernière version officielle...
