### ISSUE TITLE
Rapport perso

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#58]
J'uploaderai mon rapport perso concernant les difficultés que j'ai rencontrés demain en fin de journée.

**Comment by pierre-H** [comment]
Voilà c'est fait. Désolé du retard.
Qu'en est-il pour vous ?
Il faut qu'on avance sur ce projet !

**Comment by rcharb1** [comment]
J'ai ajouté le mien.

**Comment by pierre-H** [comment]
Superbe !

**Comment by ninja427** [comment]
J'ai ajouté mon rapport
