### ISSUE TITLE
Une petite modification ?

### ISSUE THREAD

**Issue by rcharb1** [pierre-H/optimiseur-coupe#59]
Bonjour,
Désolée de me manifester si tard... @ninja427 serait-il possible de rajouter une malheureuse instruction dans un fichier du moteur ? J'ai peur de faire des bêtises maintenant que le packaging est fait. Cela ne cause pas trop de soucis ?
Il s'agit  de remettre à 0 le compteur de tours entre chaque recherche pour ne pas obtenir une fausse erreur de dépassement de capacités à cause du cumul de ce compteur.
Il suffit de rajouter l'instruction *lim = 0; après la ligne 23 de /usr/share/cutting_optimizer/src/moteur/MoteurCalculs.cpp...

**Comment by pierre-H** [comment]
En ajouter l'onglet je vais le faire, ce sera 2 en 1 pour xavier

**Comment by ninja427** [comment]
Packaging fait !
