### ISSUE TITLE
Maquette

### ISSUE THREAD

**Issue by pierre-H** [pierre-H/optimiseur-coupe#8]
Voici ci-dessous la maquette. N'hésitez pas à me donner votre avis !

![capture1](https://framapic.org/DOu9U9AdOJFa/V9wNlm21)

![capture2](https://framapic.org/7TJwS2NvbABc/HcCjL63v)

![capture3](https://framapic.org/X21RRWPNdJJq/Hdk0kuUi)

**Comment by rcharb1** [comment]
Super, beau boulot ! 
Quelques petits commentaires : 
- "quelle est leur~~s~~ taille~~s~~" (grammaire, puisqu'il s'agit d'une même taille pour toutes les barres.
- Est-il possible de rajouter un champ demandant la perte à chaque coupe ?
- Au stade de la maquette, ce n'est pas super important, mais autant qu'elle contienne tout : rajouter les instructions de saisie : "...que vous voulez obtenir séparés par des points-virgules. Utiliser l'opérateur \* pour demander plusieurs morceaux d'une même taille"
- Est-il possible aussi d'afficher, à par le résultat graphique qui est très bon (merci Xavier), un petit bout de texte du style "morceau 1 : ... morceau 2 ... Vous avez une perte de ... mm et un rendement de ... %"
  Bonne journée !

**Comment by pierre-H** [comment]
Voilà : 

![capture4](https://framapic.org/WT12KbkQxucw/POo88yWs)

Pour le résultat, tant que je ne sais pas très bien comment je vais coder la génération du shéma, je préfère ne pas trop ajouter de détails (c'est la raison pour laquelle j'ai utilisé l'image de Xavier)

**Comment by rcharb1** [comment]
Merci beaucoup, ça me semble parfait !
Je viens de me rendre compte qu'il y a eu un petit malentendu concernant un point des spécifications : pour l'instant, le programme ne traite que des barres de taille standard, les barres de départ doivent  toutes avoir la même taille... C'est vrai que pour faire un programme plus complet, il faudrait peut-être rajouter la possibilité de rentrer plein de tailles différentes de matériau de départ... Il faut que je réfléchisse combien ça complique le programme...

**Comment by pierre-H** [comment]
J'ai pas très bien compris ... mais  il suffit de me dire ce que je dois changer et ce sera fait.

**Comment by rcharb1** [comment]
En fait, il ne s'agit pas de quelque chose à _changer_ pour l'instant, mais plutôt de quelque chose à _décider_... 
En gros, cela signifie que si j'ai **au départ** une barre de 50 cm, une barre de 1,5 m et une barre de 5m, puis-je utiliser ce programme ou non ? Je m'explique : lorsque j'ai commencé à coder, j'ai fait l'hypothèse que les barres dont l'utilisateur dispose **au départ** sont d'une taille standard sorties d'usine. Comme par exemple 10 barres de 5m ou 5 barres de 1.25 m... Cela simplifie drôlement les calculs, mais limite le champ d'application...
Il faut donc qu'on en discute ensemble...
Appelons Xavier @ninja427

**Comment by pierre-H** [comment]
Ah ok, je comprend.
Concernant les morceaux que l'utilisateur souhaite obtenir, ne serait-il pas plus logique d'avoir un champ de texte pour chaque morceau plutôt qu'une vulgaire zone de texte ?

**Comment by rcharb1** [comment]
oui, on peut faire ça, c'est vrai que c'est plus joli, et si l'utilisateur se trompe dans sa saisie, ça évite de lui refuser tout de bloc et de l'inviter à recommencer, mais plutôt de surligner le champ problématique. ça simplifie aussi les regex. Par contre, si on se sert du nombre de barres qu'il a pour savoir combien de champs lui présenter, on ne pourra pas lui donner accès à l'opérateur *...
A moins de présenter les champs de texte pour chaque morceau de manière dynamique et de décrémenter le nombre de champs de textes à afficher dès qu'on trouve l'opérateur \* dans l'un d'eux... ça me semble être le mieux...
J'ai l'impression que ce message est un peu confus... N'hésitez pas à me le dire...

**Comment by pierre-H** [comment]
Cela donnerait quelque chose comme ça (avec les boutons + et - pour ajouter des types de morceaus souhaités) : 

![capture 5](https://framapic.org/YMSpj6LGxyi6/CvG9ybif)

**Comment by rcharb1** [comment]
ça me paraît très bien, sachant que la perte peut donner lieu à un unique champ puisqu'il est probable qu'il coupe tout avec la même machine. Je propose même que ce champ soit facultatif et soit mis à 0 par défaut si l'utilisateur décide que c'est négligeable...

**Comment by ninja427** [comment]
Bonjour à tous les deux...

Désolé de ne pes m'être impliqué avant, j'étais en réunion.

Comment je vois personnellement les choses :

Un champs de saisie où l'on peut écrire par exemple "3*1123mm", avec 
dans le voisinage un bouton ajouter une entrée, pour la saisie des 
barres avant découpe. On rajouterait donc dynamiquement un champs à 
chaque fois que l'on cliquerait sur ce bouton.

Ainsi on pourrait à un moment se retrouver avec quatre champs contenant 
respectivement "3_1123mm", "4_12in", "1.52m" et "12 cm".

Exactement la même chose pour les tronçons désirés.

Ces champs pourraient même faire partie de la fenêtre principale avec 
en dessous une frame de rendu de résultats (activé par un bouton 
"appliquer").

Par contre je ne comprends pas pourquoi il faut mettre le rendement sur 
le formulaire ?

Qu'en pensez-vous ?

Le 2015-04-22 13:32, Pierre a écrit :

> Cela donnerait quelque chose comme ça (avec les boutons + et - pour
> ajouter des types de morceaus souhaités) :
> 
>  [1]
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [2].
> 
>   *
> 
> ## Links:
> 
> [1]
> 
> https://camo.githubusercontent.com/becb0e4ff22140abd406296ea8bb9a72698e09f1/68747470733a2f2f6672616d617069632e6f72672f594d53706a364c47787969362f4376473979626966
> [2] 
> https://github.com/pierre-H/optimiseur-coupe/issues/8#issuecomment-95145053

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by pierre-H** [comment]
Donc, plus quelque chose comme ça : 

![capture6](https://framapic.org/cx6VKFGMc7Lx/f2nSZIwl)

**Comment by rcharb1** [comment]
Oui, donc ça c'est bien je crois et si je comprends bien, ça veut dire qu'il faut que je modifie le programme pour calculer à partir de diverses longueurs de départ... 
Le rendement va être affiché comme **résultat** du calcul du moteur, pas dans le formulaire de départ.

**Comment by pierre-H** [comment]
Ok. D'autres modifications à faire ou on déclare cette maquette comme étant la maquette officielle :-) ?

**Comment by rcharb1** [comment]
Pour moi, c'est bon ! Je dis officiel !

**Comment by ninja427** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11976875/7274022/90547956-e8f9-11e4-8a00-d24889a8b588.png)
Et quelque chose dans ce gout là ?

**Comment by ninja427** [comment]
Il faudrait bien sûr étoffer les commentaires

**Comment by pierre-H** [comment]
Je pense qu'il vaut mieux utiliser des spinbox (champ avec des flèches comme dans mes images précédentes) pour désigner le nombre de morceau à la place de l'astérisque à moins que je ne me trompe et que **A*B** correspond à **largeur*longeur**.
Mais mettre les résultats dans la même fenêtre est tout à fait possible.

**Comment by pierre-H** [comment]
Faut-il aussi une fonction qui permettrai d'enregistrer les résultats (au format html par exemple) ?
Je ne sais pas si cela peut être intéressant pour un bricoleur de pouvoir l'enregistrer...

**Comment by ninja427** [comment]
C'est une bonne idée, les spinbox.
Enregistrer les résultats, je ne verrais ça que dans un schéma purement industriel assez rarissime où la production réutiliserait des programmes type de découpe.

**Comment by pierre-H** [comment]
Ok, alors on laisse tomber cette histoire d'enregistrement.

**Comment by pierre-H** [comment]
Donc on va plus vers quelque chose comme ça (dois-je mettre un champ **quelle est la perte ?**)

![capture7](https://framapic.org/bMrSKvtm7X6l/099TD7zV)

**Comment by ninja427** [comment]
Magnifique ! J'adore..
Le programme devant faire son maximum pour limiter la perte et laisser la chute finale la plus longue possible, la perte ne devrait pas être paramétrable (sinon à quoi bon optimiser la coupe ?).
Je répète : magnfique, tant pas l'aspect que par la concision. Cette interface est limpide pour le end-user. Es-tu d'accord avec ça Rebecca ?

**Comment by pierre-H** [comment]
Merci beaucoup @ninja427  :)

**Comment by pierre-H** [comment]
J'ai juste oublié de mettre dans les spinbox : minimum 1.

**Comment by ninja427** [comment]
Exact.
Mais il ne s'agît que d'une maquette.
Les textes aussi  seront améliorés.
Mais avec ça on a défini (après feu vert de Rebecca) les saisies et elle pourra faire évoluer le moteur.
Le programme devient convaincant pour une soutenance et surtout très réaliste car adapté aux besoins d'un véritable utilisateur final en termes d'ergonomie.

**Comment by ninja427** [comment]
Après du coup présenté comme ça pourquoi ne pas rajouter des spinboxes pour les unités ? Plus besoin des regex du coup, et on n'y perdrait pas en clarté tant qu'on reste sur ce type de présentation..

**Comment by ninja427** [comment]
Qu'en penses-tu Rebecca ?

**Comment by pierre-H** [comment]
Voila avec les unités : 

![capture7](https://framapic.org/RxI5jl9LQlcx/EczKs0BC)

**Comment by pierre-H** [comment]
Note : pour ajouter une image, j'utilise [framapic.org](https://framapic.org/) que j'ajoute en markdown. Pas besoin d'ajouter le fichier dans le repository.

**Comment by ninja427** [comment]
J'adore...

**Comment by ninja427** [comment]
Oups !!!!!!
On a oublié un champs pour la perte due à la coupe (où zéro est autorisé)

**Comment by pierre-H** [comment]
Voila avec la perte :

![capture8](https://framapic.org/eWX0RYqwVLZU/x07JBDfe)

**Comment by pierre-H** [comment]
Je dois dire que je suis fier de ma maquette :-)

**Comment by ninja427** [comment]
Moi j'aime beaucoup ! C'est vraiment très chouette 
Petit gain de place possible : mettre le bouton appliquer tout à droite de la dernière ligne ?

**Comment by pierre-H** [comment]
Ah oui, en effet, c'est une bonne idée :

![capture9](https://framapic.org/GvaIbjHZAnCo/BAzJgAsE)

**Comment by ninja427** [comment]
Ouahhhh !
Magnifique !!!!!!!!!!!!

**Comment by ninja427** [comment]
Pour les textes, suggestions (pour la version française):
Dimensions des barres avant découpe     Unité     Quantité
Dimensions des tronçons désirés              Unité     Quantité
Epaisseur de lame                      Unité

Ca devrait permettre de réduire encore l'en-tête je pense pour laisser plus de place pour la restitution des résultats. (2 lignes gagnées)

**Comment by pierre-H** [comment]
C'est bien car on avance ! (Pourquoi pas plutôt **Épaisseur de _la_ lame**)

![capture10](https://framapic.org/0HgheC7jU1mj/zcoaH5Or)

**Comment by ninja427** [comment]
Du coup les possibilités d'erreurs sont drastiquement réduites car la saisie est hyper contrôlée par cette méthode, les regex se réduisent à peau de chagrin. En résumé on aurait:
- rentrer des nombres strictement positifs pour les longueurs
  Et c'est tout concernant la saisie (à moins que vous voyez autre chose).
  Il reste par contre des notions à approfondir telles que la taille maximale des tronçons (inférieure ou égale à la taille des barres, à gérer avec les quantités), la plausibilité des valeurs entrées, etc...
  Il faut que je creuse ça, je vous donne ça au plus vite !

**Comment by ninja427** [comment]
Il ne manquerait plus que l'unité pour l'épaisseur de lame je pense (mais tu dois en avoir marre, non ?)

**Comment by pierre-H** [comment]
Pour ce qui est des nombres _strictement positifs_ c'est déjà fait. Il faut juste maintenant déterminer la valeur maximale possible.

**Comment by pierre-H** [comment]
J'ai pensé à l'unité pour l'épaisseur de la lame mais je me dit qu'une lame de 25 cm ou de 30 m d'épaisseurs c'est assez rare... non ?

**Comment by ninja427** [comment]
Pour le reste c'est parfait et tes en-têtes en gras sont du plus bel effet ! Ca rajoute de la clarté

**Comment by ninja427** [comment]
En fait c'est plutôt que ça peut être des unités anglo saxonnes... Pour le reste tu as raison, mm et inches suffiraient largement, ou on impose en mm, mais il faut le préciser (Epaisseur de lame (en mm)).

**Comment by pierre-H** [comment]
Voila :

![capture11](https://framapic.org/XewzUyluEYU5/piYxpGlW)

**Comment by ninja427** [comment]
C'est magnifique ! Ce qui m'impressionne le plus c'est la vitesse à laquelle tu nous alignes ces maquettes... Ca semble facile quand tu le fais !

**Comment by pierre-H** [comment]
C'est assez facile avec Qt Designer en effet.
Mais je pense que le véritable code je le ferai à la main bien que l'on aura le même résultat d'un point de vue graphique.

**Comment by pierre-H** [comment]
à la mais, je met je pense une heure pour faire ça.

**Comment by ninja427** [comment]
!!!!!
Etonnant !
Je pense vraiment qu'il faut que je me mette à Qt
Peut-être pour le projet de programmation graphique ?
Tu as choisi ce que tu vas faire ?
Moi je pensais au billard...

**Comment by pierre-H** [comment]
Non, je n'y ai pas encore bien réfléchi... Mais Qt est vraiment génial !

**Comment by pierre-H** [comment]
Et la doc est très bien faite !

**Comment by ninja427** [comment]
Hors sujet, avant que je rentre chez moi, ils ne parlent que de ça au boulot :
https://github.com/nvbn/thefuck
C'est rigolo...

**Comment by pierre-H** [comment]
Il y a des gens qui ont de ces idées !

**Comment by rcharb1** [comment]
Merci beaucoup et désolée pour mon absence... J'ai dû partir de là où j'avais une connexion internet et j'ai lu votre échange. C'est en effet très impressionant  et tout me paraît bien réfléchi.
Au lieu du +, je verrais bien le texte "Ajouter une saisie" proposée par Xavier, et, (désolée d'arriver après la guerre) je pense que l'idée de l'enregistrement en format HTML est une très bonne idée, moins pour réutiliser le résultat que pour les partager : imaginez l'ingénieur qui envoie les instructions aux ouvriers par exemple. Qu'en pensez-vous ?
(de mon côté, j'ai rédigé cette après-midi les tests de non régression du fichier List.cpp)
Merci encore
Rébecca

**Comment by ninja427** [comment]
Ok pour tes propositions ! Je vais essayer de regarder tes tests de régression avant ce soir, après je serai en déplacement jusqu'à samedi, je ne pourrais donc m'y recoller qu'à partir de dimanche.
A + !

**Comment by pierre-H** [comment]
Voila le résultat sans les icônes. Du coup si on propose l'enregistrement en html, alors je pense que ce serai plus avantageux de générer le graphique en html directement. Ainsi pour l'exportation ce sera directement plus simple. "**Ajouter une saisie**" ne pose aucun problème, en revanche "**Supprimer une saisie**" c'est dérangeant car en réalité c'est "**Supprimer la _dernière_ saisie**"

![capture12](https://framapic.org/r1CVxBLE0pMm/V9IKw0rk)

**Comment by pierre-H** [comment]
Question : est-ce que l'on met une limite au nombre de barres avant la découpe et de tronçons désirés ? (Je pose la question car si l'utilisateur met 35 barres et 48 tronçons sera très grande. Du coup, il faudrait un tableau avec une barre de défilement.)

**Comment by ninja427** [comment]
Le 2015-04-23 13:01, Pierre a écrit :

> Question : est-ce que l'on met une limite au nombre de barres avant
> la découpe et de tronçons désirés ? (Je pose la question car si
> l'utilisateur met 35 barres et 48 tronçons sera très grande. Du coup,
> il faudrait un tableau avec une barre de défilement.)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] 
> https://github.com/pierre-H/optimiseur-coupe/issues/8#issuecomment-95540417

J'avais personnellement envisagé la barre de défilement...
Car je ne vois pas comment on peut définir une limite maximale pour ces 
entrées.

## 

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
Je penche aussi pour la barre de défilement...
