### ISSUE TITLE
Pertinence du paramètre "perte à la coupe"

### ISSUE THREAD

**Issue by rcharb1** [pierre-H/optimiseur-coupe#9]
## Pertinence du paramètre "perte à la coupe"

Suite à notre discussion à propos du rajout de l'option de prendre en compte la perte à la coupe, j'ai réfléchi un peu plus mathématiquement à la chose pour déterminer quel pouvait être l'impact de ce paramètre sur le rendement final.
Je vous fait part de ma réflexion, dites-moi si quelque chose est faux :

Dans tous les cas, le nombre de coupes **par barre** est égal :
- Soit au nombre de tronçons qu'on a casés dans la barre, dans le cas où il y a de la perte.
- Soit à ce même nombre moins 1 si on a utilisé toute la barre.

S'il y a B barres, et que chaque coupe occasionne une perte de P, la différence entre le nombre maximal de coupes et le nombre minimal de coupes est de B seulement, et la différence de perte entre le meilleur des cas et le pire des cas est de P \* B.

Mais si l'on réfléchit à cette différence entre le meilleur des cas et le pire des cas, on se rend compte qu'elle ne réside que dans la différence qu'il y a entre le cas où **toutes** les barres ont été **complètement** utilisées et un cas où **toutes** les barres ont un bout **perdu** (qu'il a fallu couper donc qui a rajouté une coupe...)
Or, dans l'algorithme actuel, le programme choisit bien évidemment en premier un rendement de 100% pour une barre (c'est à dire pas de bout perdu, donc une coupe en moins, mais en même temps un rendement supérieur). Donc en réalité, si l'on parle de la perte à la coupe, on se rend compte que le preogramme optimise déjà la perte  liée au nombre de coupes (en tout cas, d'après ce raisonnement)...

Mais je ne pense pas qu'il s'agisse d'une raison suffisante pour abandonner complètement ce paramètre.
Pourquoi ?

Parce qu'imaginons, le cas d'un matériau extrêmement dur ou épais, dont chaque coupe nécessite un effort considérable (une équipe nombreuse, une machine performante, un temps non négligeable...), dont on préfère avoir le moins de coupes à faire, il pourrait exister (je crois, mais on peut facilement le vérifier) une situation, où la meilleure des combinaisons entraînerait un nombre de coupes plus important (de une ou deux coupes seulement) qu'une combinaison moins avantageuse. 
Ainsi, peut-être serait-il judicieux de couvrir ce cas, c'est à dire de laisser le choix à la fin entre les meilleures combinaisons en terme d'optimisation du matériau, et la meilleure combinaison en terme de minimum d'effort de coupe, sachant que le nombre de tronçons demandés étant le même dans les deux cas, le nombre de coupes ne changera pas du tout au tout !

Il est tout à fait possible que ce raisonnement ait des failles, donc vous pouvez le retourner dans tous les sens pour le mettre à l'épreuve. Si vous pensez qu'il y a quelque part une logique, je propose qu'on supprime le champ "épaisseur de la lame", mais qu'on propose tout de même à la fin s'il y a une possibilité qui optimise la coupe et n'est pas la possibilité optimale vis à vis des longueurs.

**Comment by ninja427** [comment]
Le 2015-04-23 16:32, rcharb1 a écrit :

> PERTINENCE DU PARAMÈTRE "PERTE À LA COUPE"
> 
> Suite à notre discussion à propos du rajout de l'option de prendre en
> compte la perte à la coupe, j'ai réfléchi un peu plus 
> mathématiquement
> à la chose pour déterminer quel pouvait être l'impact de ce paramètre
> sur le rendement final.
>  Je vous fait part de ma réflexion, dites-moi si quelque chose est 
> faux :
> 
> Dans tous les cas, le nombre de coupes PAR BARRE est égal :
> - Soit au nombre de tronçons qu'on a casés dans la barre, dans le
>   cas où il y a de la perte.
> - Soit à ce même nombre moins 1 si on a utilisé toute la barre.
> 
> S'il y a B barres, et que chaque coupe occasionne une perte de P, la
> différence entre le nombre maximal de coupes et le nombre minimal de
> coupes est de B seulement, et la différence de perte entre le 
> meilleur
> des cas et le pire des cas est de P \* B.
> 
> Mais si l'on réfléchit à cette différence entre le meilleur des cas
> et le pire des cas, on se rend compte qu'elle ne réside que dans la
> différence qu'il y a entre le cas où TOUTES les barres ont été
> COMPLÈTEMENT utilisées et un cas où TOUTES les barres ont un bout
> PERDU (qu'il a fallu couper donc qui a rajouté une coupe...)
>  Or, dans l'algorithme actuel, le programme choisit bien évidemment
> en premier un rendement de 100% pour une barre (c'est à dire pas de
> bout perdu, donc une coupe en moins, mais en même temps un rendement
> supérieur). Donc en réalité, si l'on parle de la perte à la coupe, on
> se rend compte que le preogramme optimise déjà la perte liée au 
> nombre
> de coupes (en tout cas, d'après ce raisonnement)...
> 
> Mais je ne pense pas qu'il s'agisse d'une raison suffisante pour
> abandonner complètement ce paramètre.
>  Pourquoi ?
> 
> Parce qu'imaginons, le cas d'un matériau extrêmement dur ou épais,
> dont chaque coupe nécessite un effort considérable (une équipe
> nombreuse, une machine performante, un temps non négligeable...), 
> dont
> on préfère avoir le moins de coupes à faire, il pourrait exister (je
> crois, mais on peut facilement le vérifier) une situation, où la
> meilleure des combinaisons entraînerait un nombre de coupes plus
> important (de une ou deux coupes seulement) qu'une combinaison moins
> avantageuse.
>  Ainsi, peut-être serait-il judicieux de couvrir ce cas, c'est à dire
> de laisser le choix à la fin entre les meilleures combinaisons en
> terme d'optimisation du matériau, et la meilleure combinaison en 
> terme
> de minimum d'effort de coupe, sachant que le nombre de tronçons
> demandés étant le même dans les deux cas, le nombre de coupes ne
> changera pas du tout au tout !
> 
> Il est tout à fait possible que ce raisonnement ait des failles, donc
> vous pouvez le retourner dans tous les sens pour le mettre à
> l'épreuve. Si vous pensez qu'il y a quelque part une logique, je
> propose qu'on supprime le champ "épaisseur de la lame", mais qu'on
> propose tout de même à la fin s'il y a une possibilité qui optimise 
> la
> coupe et n'est pas la possibilité optimale vis à vis des longueurs.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] https://github.com/pierre-H/optimiseur-coupe/issues/9

En fait ce paramètre est incontournable pour le cas suivant, pas si 
rare :
J'ai une barre de 1 m, je veux 10 tronçons de 10 cm chacun, et ma lame 
fait 1 mm d'épaisseur.
Je vous garantis que j'ai déjà été confronté à ce genre de cas de 
figure...

Après c'est contournable lors de la saisie, en additionnant directement 
l'épaisseur de lame à chaque saisie de tronçon.
Il suffit au final de penser à enlever l'épaisseur de lame à chaque 
dernier tronçon.
C'est une astuce mais je pense que ça peut simplifier le process.

Je n'ai pas le temps d'explorer ton raisonnement à fond Rebecca (mais 
il est évident que tu y as déjà beaucoup réfléchi :)), je ne peux que me 
prononcer sur la pertinence de ce paramètre dans l'immédiat.

## Bon courage (et à dimanche je pense) !!!

Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
C'est vrai, ce paramètre est nécessaire si on veut une très bonne précision, même si ça ne servira peut-être pas à l'optimisation. Merci !

**Comment by ninja427** [comment]
Le 2015-04-23 16:42, rcharb1 a écrit :

> C'est vrai, ce paramètre est nécessaire si on veut une très bonne
> précision, même si ça ne servira peut-être pas à l'optimisation. 
> Merci
> !
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] 
> https://github.com/pierre-H/optimiseur-coupe/issues/9#issuecomment-95609071
> Dans l'exemple que je viens de donner, la dernière barre ferait 9.1 cm 
> au lieu de 10cm... Le pb provient du cumul des imprécisions, et dans une 
> entreprise de meubles de jardin en acier où j'ai travaillé la précision 
> demandée était du demi millimètre sur ma machine de sectionnement de 
> barres, ce qui n'a plus rien d'étonnant de nos jours. Je sais que ça 
> complique tout, mais je ne vois pas comment justifier l'absence de ce 
> 
> ## paramètre lors de la soutenance...
> 
> Cordialement,

Xavier JANIN.

Elève 12316706

**Comment by rcharb1** [comment]
C'est tout à fait juste, et de plus, je ne pense pas que ça complique tellement que ça si l'on réfléchit à la manière d'introduire ce paramètre de la meilleure manière possible...

**Comment by rcharb1** [comment]
Donc on conclut que ce paramètre est oui pertinent et on le rajoutera dans un avenir proche, donc je ferme l'issue.
